//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using Newline53.Sdk;
using Newline53.Sdk.Models;
using Newline53.Sdk.Models.Components;
using Newline53.Sdk.Models.Errors;
using Newline53.Sdk.Models.Requests;
using Newline53.Sdk.Utils;
using Models = Newline53.Sdk.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Numerics;
using System.Threading.Tasks;
using Xunit;

public class TransfersTests
{

    [Fact]
    public async Task TestTransfers_ListTransfersTransactions()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("listTransfers-transactions");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        ListTransfersRequest req = new ListTransfersRequest() {
            CustomerUid = "uKxmLxUEiSj5h4M3",
            ExternalUid = "client-generated-id",
            PoolUid = "wTSMX1GubP21ev2h",
            SyntheticAccountUid = "4XkJnsfHsuqrxmeX",
        };

        var res = await sdk.Transfers.ListAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferAch()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-ach");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            Ach = new CreateTransferAchRequest() {
                OriginatorName = "Mr. Hyyt Meiser",
                CompanyId = "HJK867",
                CompanyDiscretionaryData = "Some data",
                Prenote = false,
                SecCode = CreateTransferSecCodeRequest.Ccd,
                PaymentType = CreateTransferPaymentTypeRequest.S,
                EntryDescription = "ACH Entry",
                ServiceProcessing = CreateTransferServiceProcessingRequest.Standard,
                EffectiveEntryDate = "2023-12-21",
                IdNumber = "4270465600",
                Addenda = "Having said that, this",
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferInstantPayment()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-instant_payment");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            InstantPayment = new CreateTransferInstantPaymentRequest() {
                InstantPaymentTransmitter = new CreateTransferInstantPaymentTransmitter() {
                    Name = "Royalty Asset Management",
                    TransmitterIdentifier = "123456789",
                    StreetNumber = "123",
                    Street1 = "Abc St.",
                    City = "Boring",
                    State = "OR",
                    PostalCode = "97009",
                    Country = null,
                },
                Memo = "To unfreeze the prince's assets",
                PurposeOfPayment = CreateTransferPurposeOfPaymentRequest.Payr,
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferWire()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-wire");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            Wire = new CreateTransferWireRequest() {
                IntermediaryBankAddress = new CreateTransferIntermediaryBankAddressUnstructuredAddressRequest() {
                    Line1 = "345 Def Ave",
                    Line2 = "San Francisco",
                    Line3 = "CA 94016",
                    Country = "US",
                },
                IntermediaryBankName = "Fidelity Fiduciary Bank",
                IntermediaryBankRoutingNumber = "923456789",
                WireInstructions = "Please send ASAP",
                WireTransmitter = CreateTransferWireTransmitterRequest.CreateCreateTransferWireTransmitterUnstructuredAddress(new CreateTransferWireTransmitterUnstructuredAddress() {
                    Line1 = "123 Abc St.",
                    Country = "US",
                    Name = "Top Tier Tacos",
                    TransmitterIdentifier = "123456789",
                }),
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferAchTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-ach_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            Ach = new CreateTransferAchRequest() {
                OriginatorName = "J. Fred Muggs",
                CompanyId = "ABC-123456",
                CompanyDiscretionaryData = "ABC.123",
                Prenote = false,
                SecCode = CreateTransferSecCodeRequest.Cie,
                PaymentType = CreateTransferPaymentTypeRequest.St,
                EntryDescription = "ACH Entry",
                ServiceProcessing = CreateTransferServiceProcessingRequest.Sameday,
                EffectiveEntryDate = "2023-12-01",
                IdNumber = "4270465600",
            },
            InstantPayment = new CreateTransferInstantPaymentRequest() {
                InstantPaymentTransmitter = new CreateTransferInstantPaymentTransmitter() {
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                    StreetNumber = "123abc",
                    Street1 = "Abc St.",
                    City = "Chicago",
                    State = "IL",
                    PostalCode = "60301",
                    Country = null,
                },
                Memo = "For the 6-5-23 shipment of pineapple popsicles",
                PurposeOfPayment = CreateTransferPurposeOfPaymentRequest.Payr,
            },
            Wire = new CreateTransferWireRequest() {
                IntermediaryBankAddress = new CreateTransferIntermediaryBankAddressUnstructuredAddressRequest() {
                    Line1 = "345 Def Ave",
                    Line2 = "San Francisco",
                    Line3 = "CA 94016",
                    Country = "US",
                },
                IntermediaryBankName = "Fidelity Fiduciary Bank",
                IntermediaryBankRoutingNumber = "923456789",
                WireInstructions = "Send ASAP",
                WireTransmitter = CreateTransferWireTransmitterRequest.CreateCreateTransferWireTransmitterUnstructuredAddress(new CreateTransferWireTransmitterUnstructuredAddress() {
                    Line1 = "123 Abc St.",
                    Line2 = "Boring, Oregon 97009",
                    Line3 = null,
                    Country = "US",
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                }),
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferInstantPaymentTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-instant_payment_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            Ach = new CreateTransferAchRequest() {
                OriginatorName = "J. Fred Muggs",
                CompanyId = "ABC-123456",
                CompanyDiscretionaryData = "ABC.123",
                Prenote = false,
                SecCode = CreateTransferSecCodeRequest.Cie,
                PaymentType = CreateTransferPaymentTypeRequest.St,
                EntryDescription = "ACH Entry",
                ServiceProcessing = CreateTransferServiceProcessingRequest.Sameday,
                EffectiveEntryDate = "2023-12-01",
                IdNumber = "4270465600",
            },
            InstantPayment = new CreateTransferInstantPaymentRequest() {
                InstantPaymentTransmitter = new CreateTransferInstantPaymentTransmitter() {
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                    StreetNumber = "123abc",
                    Street1 = "Abc St.",
                    City = "Chicago",
                    State = "IL",
                    PostalCode = "60301",
                    Country = null,
                },
                Memo = "For the 6-5-23 shipment of pineapple popsicles",
                PurposeOfPayment = CreateTransferPurposeOfPaymentRequest.Payr,
            },
            Wire = new CreateTransferWireRequest() {
                IntermediaryBankAddress = new CreateTransferIntermediaryBankAddressUnstructuredAddressRequest() {
                    Line1 = "345 Def Ave",
                    Line2 = "San Francisco",
                    Line3 = "CA 94016",
                    Country = "US",
                },
                IntermediaryBankName = "Fidelity Fiduciary Bank",
                IntermediaryBankRoutingNumber = "923456789",
                WireInstructions = "Send ASAP",
                WireTransmitter = CreateTransferWireTransmitterRequest.CreateCreateTransferWireTransmitterUnstructuredAddress(new CreateTransferWireTransmitterUnstructuredAddress() {
                    Line1 = "123 Abc St.",
                    Line2 = "Boring, Oregon 97009",
                    Line3 = null,
                    Country = "US",
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                }),
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferWireTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-wire_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            Ach = new CreateTransferAchRequest() {
                OriginatorName = "J. Fred Muggs",
                CompanyId = "ABC-123456",
                CompanyDiscretionaryData = "ABC.123",
                Prenote = false,
                SecCode = CreateTransferSecCodeRequest.Cie,
                PaymentType = CreateTransferPaymentTypeRequest.St,
                EntryDescription = "ACH Entry",
                ServiceProcessing = CreateTransferServiceProcessingRequest.Sameday,
                EffectiveEntryDate = "2023-12-01",
                IdNumber = "4270465600",
            },
            InstantPayment = new CreateTransferInstantPaymentRequest() {
                InstantPaymentTransmitter = new CreateTransferInstantPaymentTransmitter() {
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                    StreetNumber = "123abc",
                    Street1 = "Abc St.",
                    City = "Chicago",
                    State = "IL",
                    PostalCode = "60301",
                    Country = null,
                },
                Memo = "For the 6-5-23 shipment of pineapple popsicles",
                PurposeOfPayment = CreateTransferPurposeOfPaymentRequest.Payr,
            },
            Wire = new CreateTransferWireRequest() {
                IntermediaryBankAddress = new CreateTransferIntermediaryBankAddressUnstructuredAddressRequest() {
                    Line1 = "345 Def Ave",
                    Line2 = "San Francisco",
                    Line3 = "CA 94016",
                    Country = "US",
                },
                IntermediaryBankName = "Fidelity Fiduciary Bank",
                IntermediaryBankRoutingNumber = "923456789",
                WireInstructions = "Send ASAP",
                WireTransmitter = CreateTransferWireTransmitterRequest.CreateCreateTransferWireTransmitterUnstructuredAddress(new CreateTransferWireTransmitterUnstructuredAddress() {
                    Line1 = "123 Abc St.",
                    Line2 = "Boring, Oregon 97009",
                    Line3 = null,
                    Country = "US",
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                }),
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_GetTransferAchTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getTransfer-ach_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        var res = await sdk.Transfers.GetAsync(uid: "<id>");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_GetTransferInstantPaymentTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getTransfer-instant_payment_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        var res = await sdk.Transfers.GetAsync(uid: "<id>");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_GetTransferWireTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getTransfer-wire_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        var res = await sdk.Transfers.GetAsync(uid: "<id>");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_GetTransferCanceledTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getTransfer-canceled_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        var res = await sdk.Transfers.GetAsync(uid: "<id>");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_PutTransfersUidCancelCanceledTransfer()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("put_/transfers/{uid}/cancel-canceled_transfer");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        var res = await sdk.Transfers.CancelAsync(
            uid: "<id>",
            body: new PutTransfersUidCancelRequestBody() {
                AuthorizedRepresentativeName = "Swee'Pea",
                CancellationReason = "Transfer submitted by accident",
            }
        );

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_CreateTransferWireTransferStructured()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("createTransfer-wire_transfer_structured");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        CreateTransferRequest req = new CreateTransferRequest() {
            ExternalUid = "partner-generated-id",
            SourceSyntheticAccountUid = "4XkJnsfHsuqrxmeX",
            DestinationSyntheticAccountUid = "exMDShw6yM3NHLYV",
            InitiatingCustomerUid = "iDtmSA52zRhgN4iy",
            DestinationCustomerUid = "iDtmSA52zRhgN4iy",
            InitiatorType = CreateTransferInitiatorTypeRequest.Customer,
            UsdTransferAmount = "12.34",
            Ach = new CreateTransferAchRequest() {
                OriginatorName = "J. Fred Muggs",
                CompanyId = "ABC-123456",
                CompanyDiscretionaryData = "ABC.123",
                Prenote = false,
                SecCode = CreateTransferSecCodeRequest.Cie,
                PaymentType = CreateTransferPaymentTypeRequest.St,
                EntryDescription = "ACH Entry",
                ServiceProcessing = CreateTransferServiceProcessingRequest.Sameday,
                EffectiveEntryDate = "2023-12-01",
                IdNumber = "4270465600",
            },
            InstantPayment = new CreateTransferInstantPaymentRequest() {
                InstantPaymentTransmitter = new CreateTransferInstantPaymentTransmitter() {
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                    StreetNumber = "123abc",
                    Street1 = "Abc St.",
                    City = "Chicago",
                    State = "IL",
                    PostalCode = "60301",
                    Country = null,
                },
                Memo = "For the 6-5-23 shipment of pineapple popsicles",
                PurposeOfPayment = CreateTransferPurposeOfPaymentRequest.Payr,
            },
            Wire = new CreateTransferWireRequest() {
                IntermediaryBankAddress = new CreateTransferIntermediaryBankAddressUnstructuredAddressRequest() {
                    Line1 = "345 Def Ave",
                    Line2 = "San Francisco",
                    Line3 = "CA 94016",
                    Country = "US",
                },
                IntermediaryBankName = "Fidelity Fiduciary Bank",
                IntermediaryBankRoutingNumber = "923456789",
                WireInstructions = "Send ASAP",
                WireTransmitter = CreateTransferWireTransmitterRequest.CreateCreateTransferWireTransmitterUnstructuredAddress(new CreateTransferWireTransmitterUnstructuredAddress() {
                    Line1 = "123 Abc St.",
                    Line2 = "Boring, Oregon 97009",
                    Line3 = null,
                    Country = "US",
                    Name = "Marge's Roofing Inc",
                    TransmitterIdentifier = "123456789012ABC",
                }),
            },
        };

        var res = await sdk.Transfers.CreateAsync(req);

        // handle response
        Assert.NotNull(res);
        Assert.Equal(201, (int)res.HttpMeta.Response.StatusCode);
    }

    [Fact]
    public async Task TestTransfers_GetTransferWireTransferStructured()
    {

        var testHttpClient = CommonHelpers.CreateTestHTTPClient("getTransfer-wire_transfer_structured");
        var sdk = new NewlineSDK(
            serverUrl: Environment.GetEnvironmentVariable("TEST_SERVER_URL") ?? "http://localhost:18080",
            security: new Security() {
                ProgramUid = "NEWLINE_PROGRAM_UID",
                HmacKey = "NEWLINE_HMAC_KEY",
            },
            client: testHttpClient
        );
        var res = await sdk.Transfers.GetAsync(uid: "<id>");

        // handle response
        Assert.NotNull(res);
        Assert.Equal(200, (int)res.HttpMeta.Response.StatusCode);
    }
}
