//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Errors
{
    using Newline53.Sdk.Models.Components;
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Net.Http;

    public class GetReturnsUidForbiddenExceptionPayload
    {
        /// <summary>
        /// The DateTime at which this Return was created.
        /// </summary>
        [JsonProperty("created_at")]
        public string? CreatedAt { get; set; }

        /// <summary>
        /// Client supplied unique identifier. It must be unique within the customer. If the same value is given, no new resource will be created.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; }

        /// <summary>
        /// The transaction to be returned.
        /// </summary>
        [JsonProperty("original_transaction_uid")]
        public string? OriginalTransactionUid { get; set; }

        /// <summary>
        /// The UID of the customer requesting a return.
        /// </summary>
        [JsonProperty("customer_uid")]
        public string? CustomerUid { get; set; }

        /// <summary>
        /// Type of the customer requesting a return.
        /// </summary>
        [JsonProperty("requestor_type")]
        public ForbiddenRequestorType? RequestorType { get; set; }

        /// <summary>
        /// Freeform text (up to 140 characters) documenting the reason for return. For wire returns, this value will be sent to the other bank.
        /// </summary>
        [JsonProperty("return_reason")]
        public string? ReturnReason { get; set; }

        /// <summary>
        /// The transaction returning the funds.
        /// </summary>
        [JsonProperty("return_transaction_uid")]
        public string? ReturnTransactionUid { get; set; }

        /// <summary>
        /// A value indicating the overall status of the Return.
        /// </summary>
        [JsonProperty("status")]
        public ForbiddenStatus? Status { get; set; }

        /// <summary>
        /// Unique identifier for the Return.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// Denied access to Returns.
    /// </summary>
    public class GetReturnsUidForbiddenException : NewlineSDKException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public GetReturnsUidForbiddenExceptionPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.CreatedAt instead.")]
        public string? CreatedAt { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.ExternalUid instead.")]
        public string? ExternalUid { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.OriginalTransactionUid instead.")]
        public string? OriginalTransactionUid { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.CustomerUid instead.")]
        public string? CustomerUid { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.RequestorType instead.")]
        public ForbiddenRequestorType? RequestorType { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.ReturnReason instead.")]
        public string? ReturnReason { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.ReturnTransactionUid instead.")]
        public string? ReturnTransactionUid { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.Status instead.")]
        public ForbiddenStatus? Status { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.Uid instead.")]
        public string? Uid { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsUidForbiddenException.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public GetReturnsUidForbiddenException(
            GetReturnsUidForbiddenExceptionPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ) : base("API error occurred", request, response, body)
        {
            Payload = payload;

#pragma warning disable CS0618
            CreatedAt = payload.CreatedAt;
            ExternalUid = payload.ExternalUid;
            OriginalTransactionUid = payload.OriginalTransactionUid;
            CustomerUid = payload.CustomerUid;
            RequestorType = payload.RequestorType;
            ReturnReason = payload.ReturnReason;
            ReturnTransactionUid = payload.ReturnTransactionUid;
            Status = payload.Status;
            Uid = payload.Uid;
            HttpMeta = payload.HttpMeta;
#pragma warning restore CS0618
        }
    }
}