//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Errors
{
    using Newline53.Sdk.Models.Components;
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;

    public class GetReturnsForbiddenExceptionPayload
    {
        [JsonProperty("errors")]
        public List<GetReturnsForbiddenError>? Errors { get; set; }

        /// <summary>
        /// HTTP Status Code.
        /// </summary>
        [JsonProperty("status")]
        public long? Status { get; set; }

        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;
    }

    /// <summary>
    /// Denied access to Returns.
    /// </summary>
    public class GetReturnsForbiddenException : NewlineSDKException
    {
        /// <summary>
        ///  The original data that was passed to this exception.
        /// </summary>
        public GetReturnsForbiddenExceptionPayload Payload { get; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsForbiddenException.Payload.Errors instead.")]
        public List<GetReturnsForbiddenError>? Errors { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsForbiddenException.Payload.Status instead.")]
        public long? Status { get; set; }

        [Obsolete("This field will be removed in a future release, please migrate away from it as soon as possible. Use GetReturnsForbiddenException.Payload.HttpMeta instead.")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        public GetReturnsForbiddenException(
            GetReturnsForbiddenExceptionPayload payload,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ) : base("API error occurred", request, response, body)
        {
            Payload = payload;

#pragma warning disable CS0618
            Errors = payload.Errors;
            Status = payload.Status;
            HttpMeta = payload.HttpMeta;
#pragma warning restore CS0618
        }
    }
}