//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk
{
    using Newline53.Sdk.Hooks;
    using Newline53.Sdk.Models.Components;
    using Newline53.Sdk.Models.Errors;
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newline53.Sdk.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// The Authentication section explains how to securely interact with Newline's API using access tokens and static IP addresses. Learn how to generate and refresh tokens to access protected resources.  <br/>
    /// <br/>
    /// **Endpoints:**<br/>
    /// <br/>
    /// - POST <a href="https://developers.newline53.com/reference/post_auth">Generate an authentication token: POST /auth</a>
    /// <br/>
    /// Newline requires access tokens and static IP addresses for authentication and authorization when requesting any resource endpoints. <a href="https://developers.newline53.com/reference/post_auth">POST /auth</a> is used to obtain and refresh the required access tokens. Please work with your Relationship Team or the Newline Team in all environments to set up the IP Allowlist for your Program.  <br/>
    /// To obtain an access token, you must submit a refresh token. After a program is set up, Newline will share your Program UID and HMAC key offline. These values are required for the refresh token and access token requests.<br/>
    /// <br/>
    /// ## Auth Flow<br/>
    /// <br/>
    /// The authentication flow is as follows:<br/>
    /// <br/>
    /// 1. Create a JWT using the following claim:<br/>
    /// ```<br/>
    /// {<br/>
    ///   "iat": &lt;current Epoch time&gt;,<br/>
    ///   "sub": &lt;Program UID&gt;<br/>
    /// }<br/>
    ///  ```<br/>
    /// <br/>
    /// 1. Sign the JWT to create a JWS with the shared key using HS512 / SHA-512.<br/>
    /// <br/>
    /// 2. Exchange for an access token by sending a request to <a href="https://developers.newline53.com/reference/post_auth">POST /auth</a>, using the JWS in the `Authorization` header.<br/>
    /// <br/>
    /// 3. Access resources through other endpoints using the returned token in the `Authorization` header for up to 8 hours.<br/>
    /// <br/>
    /// 4. Repeat the process as needed to continue authenticating successfully.<br/>
    /// <br/>
    /// &gt; **Note** <br/>
    /// &gt; If a new access token is requested within the 8 hours of a previous token being successfully exchanged, the new token will still be generated. This does not expire the last token, and both tokens are usable simultaneously until their respective time is up. However, it is encouraged to use the new token and discard the old one if possible, as this behavior may change in the future.
    /// </summary>
    public interface IAuth
    {
        /// <summary>
        /// Generate an authentication token.
        /// </summary>
        /// <remarks>
        /// An access token can be generated by providing a refresh token. The generated token then can be used as an authentication token to access resources for up to 8 hours.<br/>
        /// <br/>
        /// The Client will need to provide a JWS, its payload containing Program UID as `sub` (subject) and current Epoch time as `iat` (issued at timestamp), signed by an HMAC that has been shared offline previously using HS512. See the above guide for more details.<br/>
        /// <br/>
        /// When Newline processes the `POST /auth` request, it validates that the `iat` claim is current. A 30-second difference is allowed to account for clock skew. Nevertheless, it is important that the refresh token be submitted as quickly as possible after it is generated to avoid failure in receiving an access token. Note that the returned access token is a valid JWS following `auth-` and the whole value (`auth-header.payload.signature`) must be provided in the `Authorization` header when making requests to other endpoints.
        /// </remarks>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="GenerateAuthTokenResponse"/> response envelope when completed.</returns>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public Task<GenerateAuthTokenResponse> GenerateTokenAsync(CancellationToken? cancellationToken = null);
    }

    /// <summary>
    /// The Authentication section explains how to securely interact with Newline's API using access tokens and static IP addresses. Learn how to generate and refresh tokens to access protected resources.  <br/>
    /// <br/>
    /// **Endpoints:**<br/>
    /// <br/>
    /// - POST <a href="https://developers.newline53.com/reference/post_auth">Generate an authentication token: POST /auth</a>
    /// <br/>
    /// Newline requires access tokens and static IP addresses for authentication and authorization when requesting any resource endpoints. <a href="https://developers.newline53.com/reference/post_auth">POST /auth</a> is used to obtain and refresh the required access tokens. Please work with your Relationship Team or the Newline Team in all environments to set up the IP Allowlist for your Program.  <br/>
    /// To obtain an access token, you must submit a refresh token. After a program is set up, Newline will share your Program UID and HMAC key offline. These values are required for the refresh token and access token requests.<br/>
    /// <br/>
    /// ## Auth Flow<br/>
    /// <br/>
    /// The authentication flow is as follows:<br/>
    /// <br/>
    /// 1. Create a JWT using the following claim:<br/>
    /// ```<br/>
    /// {<br/>
    ///   "iat": &lt;current Epoch time&gt;,<br/>
    ///   "sub": &lt;Program UID&gt;<br/>
    /// }<br/>
    ///  ```<br/>
    /// <br/>
    /// 1. Sign the JWT to create a JWS with the shared key using HS512 / SHA-512.<br/>
    /// <br/>
    /// 2. Exchange for an access token by sending a request to <a href="https://developers.newline53.com/reference/post_auth">POST /auth</a>, using the JWS in the `Authorization` header.<br/>
    /// <br/>
    /// 3. Access resources through other endpoints using the returned token in the `Authorization` header for up to 8 hours.<br/>
    /// <br/>
    /// 4. Repeat the process as needed to continue authenticating successfully.<br/>
    /// <br/>
    /// &gt; **Note** <br/>
    /// &gt; If a new access token is requested within the 8 hours of a previous token being successfully exchanged, the new token will still be generated. This does not expire the last token, and both tokens are usable simultaneously until their respective time is up. However, it is encouraged to use the new token and discard the old one if possible, as this behavior may change in the future.
    /// </summary>
    public class Auth : IAuth
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        public Auth(SDKConfig config)
        {
            SDKConfiguration = config;
        }

        /// <summary>
        /// Generate an authentication token.
        /// </summary>
        /// <remarks>
        /// An access token can be generated by providing a refresh token. The generated token then can be used as an authentication token to access resources for up to 8 hours.<br/>
        /// <br/>
        /// The Client will need to provide a JWS, its payload containing Program UID as `sub` (subject) and current Epoch time as `iat` (issued at timestamp), signed by an HMAC that has been shared offline previously using HS512. See the above guide for more details.<br/>
        /// <br/>
        /// When Newline processes the `POST /auth` request, it validates that the `iat` claim is current. A 30-second difference is allowed to account for clock skew. Nevertheless, it is important that the refresh token be submitted as quickly as possible after it is generated to avoid failure in receiving an access token. Note that the returned access token is a valid JWS following `auth-` and the whole value (`auth-header.payload.signature`) must be provided in the `Authorization` header when making requests to other endpoints.
        /// </remarks>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="GenerateAuthTokenResponse"/> response envelope when completed.</returns>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async Task<GenerateAuthTokenResponse> GenerateTokenAsync(CancellationToken? cancellationToken = null)
        {
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = baseUrl + "/auth";

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "generateAuthToken", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if (responseStatusCode == 201)
            {
                if (Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GenerateAuthTokenResponseBody obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<GenerateAuthTokenResponseBody>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GenerateAuthTokenResponseBody.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new GenerateAuthTokenResponse() {
                        HttpMeta = new Models.Components.HTTPMetadata() {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if (responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if (responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }
    }
}