//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk
{
    using Newline53.Sdk.Hooks;
    using Newline53.Sdk.Models.Components;
    using Newline53.Sdk.Models.Errors;
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newline53.Sdk.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Products represent financial services available in your program. Discover onboarding requirements, prerequisites, and detailed product configurations.<br/>
    /// <br/>
    /// **Endpoints:**<br/>
    /// <br/>
    /// - GET <a href="https://developers.newline53.com/reference/get_products">List Products: GET /products</a>
    ///     <br/>
    /// - GET <a href="https://developers.newline53.com/reference/get_products-uid">Get a single Product: GET /products/{uid}</a>
    /// <br/>
    /// The Products endpoint represents the financial products available to your Customers. It exposes the accounts, compliance, and Customer Profile Requirements necessary for your Customer to access the Product. For some programs, a customer must onboard one product before another product is made available. Newline will work with clients to define the required Product onboarding sequence as part of your Program.<br/>
    /// <br/>
    /// Use the Products endpoint to view the Products available to your Program and the prerequisite information or actions that must be taken for a Customer to access the Product.<br/>
    /// <br/>
    /// For more information about Newline's products and their utilization, please refer to the <a href="https://developers.newline53.com/docs/product-programs">Products Programs</a> guides.
    /// </summary>
    public interface IProducts
    {
        /// <summary>
        /// List Products.
        /// </summary>
        /// <remarks>
        /// Products filtered by the given parameters.
        /// </remarks>
        /// <param name="programUid">Only return Products belonging to the submitted Program.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="ListProductsResponse"/> response envelope when completed.</returns>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public Task<ListProductsResponse> ListAsync(
            string? programUid = null,
            CancellationToken? cancellationToken = null
        );

        /// <summary>
        /// Get a single Product.
        /// </summary>
        /// <remarks>
        /// Retrieve overall status about a Product as well as its configuration, availability, and any associated metadata.
        /// </remarks>
        /// <param name="uid">Newline-generated unique id resource specific to the current endpoint.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="GetProductResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="uid"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public Task<GetProductResponse> GetAsync(string uid, CancellationToken? cancellationToken = null);
    }

    /// <summary>
    /// Products represent financial services available in your program. Discover onboarding requirements, prerequisites, and detailed product configurations.<br/>
    /// <br/>
    /// **Endpoints:**<br/>
    /// <br/>
    /// - GET <a href="https://developers.newline53.com/reference/get_products">List Products: GET /products</a>
    ///     <br/>
    /// - GET <a href="https://developers.newline53.com/reference/get_products-uid">Get a single Product: GET /products/{uid}</a>
    /// <br/>
    /// The Products endpoint represents the financial products available to your Customers. It exposes the accounts, compliance, and Customer Profile Requirements necessary for your Customer to access the Product. For some programs, a customer must onboard one product before another product is made available. Newline will work with clients to define the required Product onboarding sequence as part of your Program.<br/>
    /// <br/>
    /// Use the Products endpoint to view the Products available to your Program and the prerequisite information or actions that must be taken for a Customer to access the Product.<br/>
    /// <br/>
    /// For more information about Newline's products and their utilization, please refer to the <a href="https://developers.newline53.com/docs/product-programs">Products Programs</a> guides.
    /// </summary>
    public class Products : IProducts
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        public Products(SDKConfig config)
        {
            SDKConfiguration = config;
        }

        /// <summary>
        /// List Products.
        /// </summary>
        /// <remarks>
        /// Products filtered by the given parameters.
        /// </remarks>
        /// <param name="programUid">Only return Products belonging to the submitted Program.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="ListProductsResponse"/> response envelope when completed.</returns>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async Task<ListProductsResponse> ListAsync(
            string? programUid = null,
            CancellationToken? cancellationToken = null
        )
        {
            var request = new ListProductsRequest() {
                ProgramUid = programUid,
            };

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/products", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "listProducts", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if (responseStatusCode == 200)
            {
                if (Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    ListProductsResponseBody obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<ListProductsResponseBody>(httpResponseBody, NullValueHandling.Include);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into ListProductsResponseBody.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new ListProductsResponse() {
                        HttpMeta = new Models.Components.HTTPMetadata() {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if (responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if (responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

        /// <summary>
        /// Get a single Product.
        /// </summary>
        /// <remarks>
        /// Retrieve overall status about a Product as well as its configuration, availability, and any associated metadata.
        /// </remarks>
        /// <param name="uid">Newline-generated unique id resource specific to the current endpoint.</param>
        /// <param name="cancellationToken">An optional cancellation token to signal when the operation should be aborted.</param>
        /// <returns>An awaitable task that returns a <see cref="GetProductResponse"/> response envelope when completed.</returns>
        /// <exception cref="ArgumentNullException">The required parameter <paramref name="uid"/> is null.</exception>
        /// <exception cref="OperationCanceledException">The operation was aborted via the provided cancellation token.</exception>
        /// <exception cref="HttpRequestException">The HTTP request failed due to network issues.</exception>
        /// <exception cref="ResponseValidationException">The response body could not be deserialized.</exception>
        /// <exception cref="APIException">Default API Exception. Thrown when the API returns a 4XX or 5XX response.</exception>
        public async Task<GetProductResponse> GetAsync(string uid, CancellationToken? cancellationToken = null)
        {
            if (uid == null) throw new ArgumentNullException(nameof(uid));

            var request = new GetProductRequest() {
                Uid = uid,
            };

            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = URLBuilder.Build(baseUrl, "/products/{uid}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (!httpRequest.Headers.Contains("Accept"))
            {
                httpRequest.Headers.Add("Accept", "application/json");
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "getProduct", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);

            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await SDKConfiguration.Client.SendAsync(httpRequest, cancellationToken);
                int _statusCode = (int)httpResponse.StatusCode;

                if (_statusCode >= 400 && _statusCode < 500 || _statusCode >= 500 && _statusCode < 600)
                {
                    var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (_httpResponse != null)
                    {
                        httpResponse = _httpResponse;
                    }
                }
            }
            catch (Exception _hookError)
            {
                var _httpResponse = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, _hookError);
                if (_httpResponse != null)
                {
                    httpResponse = _httpResponse;
                }
                else
                {
                    throw;
                }
            }

            httpResponse = await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if (responseStatusCode == 200)
            {
                if (Utilities.IsContentTypeMatch("application/json", contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    GetProductResponseBody obj;
                    try
                    {
                        obj = ResponseBodyDeserializer.DeserializeNotNull<GetProductResponseBody>(httpResponseBody, NullValueHandling.Ignore);
                    }
                    catch (Exception ex)
                    {
                        throw new ResponseValidationException("Failed to deserialize response body into GetProductResponseBody.", httpRequest, httpResponse, httpResponseBody, ex);
                    }

                    var response = new GetProductResponse() {
                        HttpMeta = new Models.Components.HTTPMetadata() {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Headers = Utilities.CollectHeaders(httpResponse.Headers)
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.APIException("Unknown content type received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if (responseStatusCode >= 400 && responseStatusCode < 500)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if (responseStatusCode >= 500 && responseStatusCode < 600)
            {
                throw new Models.Errors.APIException("API error occurred", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            throw new Models.Errors.APIException("Unknown status code received", httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }
    }
}