//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The name of the Synthetic Account Category associated with the Synthetic Account Type for this account. Refer to the Synthetic Account Type for details.
    /// </summary>
    public enum CreateSyntheticAccountSyntheticAccountCategory
    {
        [JsonProperty("general")] General,
        [JsonProperty("ach_external")] AchExternal,
        [JsonProperty("instant_payments_external")] InstantPaymentsExternal,
        [JsonProperty("wire_external")] WireExternal,
    }

    public static class CreateSyntheticAccountSyntheticAccountCategoryExtension
    {
        public static string Value(this CreateSyntheticAccountSyntheticAccountCategory value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreateSyntheticAccountSyntheticAccountCategory ToEnum(this string value)
        {
            foreach (var field in typeof(CreateSyntheticAccountSyntheticAccountCategory).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreateSyntheticAccountSyntheticAccountCategory)
                    {
                        return (CreateSyntheticAccountSyntheticAccountCategory)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreateSyntheticAccountSyntheticAccountCategory");
        }
    }
}