//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class CreateCustomerRequest
    {
        /// <summary>
        /// The type of Customer. Defaults to `primary`.
        /// </summary>
        [JsonProperty("customer_type")]
        public CustomerTypeRequest? CustomerType { get; set; }

        /// <summary>
        /// The UID of the Primary Customer with whom this Secondary Customer will be affiliated. Required for and only applicable to requests with customer_type `secondary`. Cannot be updated later from the initial value.
        /// </summary>
        [JsonProperty("primary_customer_uid")]
        public string? PrimaryCustomerUid { get; set; } = null;

        /// <summary>
        /// Indicates whether the client has already performed identity verification of the Customer. The client's Program must be configured to accept this value. All Customers in a Program configured for this value must submit true in this field to complete onboarding. This value defaults to `false`.
        /// </summary>
        [JsonProperty("client_verified")]
        public bool? ClientVerified { get; set; } = null;

        /// <summary>
        /// An optional Customer identifier supplied by the Partner. If supplied, must be unique among the collection of all Partner's Customers.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; } = null;

        /// <summary>
        /// Email of the Customer.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; } = null;

        [JsonProperty("details")]
        public CreateCustomerDetailsRequest? Details { get; set; }
    }
}