//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Contains Instant Payment-specific information. Only populated if the Synthetic Account is in the `instant_payment_external` category.
    /// </summary>
    public class CreateSyntheticAccountInstantPaymentRequest
    {
        /// <summary>
        /// Address of the business or individual who owns the external account.
        /// </summary>
        [JsonProperty("counterparty_address")]
        public CreateSyntheticAccountInstantPaymentCounterpartyAddressRequest CounterpartyAddress { get; set; } = default!;

        /// <summary>
        /// Name of the business or individual who owns the counterparty Account.
        /// </summary>
        [JsonProperty("counterparty_name")]
        public string CounterpartyName { get; set; } = default!;

        /// <summary>
        /// Email address of the counterparty.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; } = null;

        /// <summary>
        /// Exactly 10 digits long (no hyphens, parentheses, or spaces).
        /// </summary>
        [JsonProperty("phone")]
        public string? Phone { get; set; } = null;
    }
}