//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Recurring (R), single entry (S), or standing authorization entry (ST). If no value is provided, the default value populated in the NACHA file is for a single entry.
    /// </summary>
    public enum CreateTransferPaymentTypeResponse
    {
        [JsonProperty("R")] R,
        [JsonProperty("S")] S,
        [JsonProperty("ST")] St,
    }

    public static class CreateTransferPaymentTypeResponseExtension
    {
        public static string Value(this CreateTransferPaymentTypeResponse value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CreateTransferPaymentTypeResponse ToEnum(this string value)
        {
            foreach (var field in typeof(CreateTransferPaymentTypeResponse).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CreateTransferPaymentTypeResponse)
                    {
                        return (CreateTransferPaymentTypeResponse)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CreateTransferPaymentTypeResponse");
        }
    }
}