//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The type of Customer. Defaults to `primary`.
    /// </summary>
    public enum CustomerTypeRequest
    {
        [JsonProperty("primary")] Primary,
        [JsonProperty("secondary")] Secondary,
        [JsonProperty("sole_proprietor")] SoleProprietor,
    }

    public static class CustomerTypeRequestExtension
    {
        public static string Value(this CustomerTypeRequest value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static CustomerTypeRequest ToEnum(this string value)
        {
            foreach (var field in typeof(CustomerTypeRequest).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is CustomerTypeRequest)
                    {
                        return (CustomerTypeRequest)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum CustomerTypeRequest");
        }
    }
}