//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Customer has begun the archive process.
    /// </summary>
    public class DeleteCustomerResponseBody
    {
        /// <summary>
        /// Newline-generated unique id resource specific to the current endpoint.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        /// <summary>
        /// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; }

        /// <summary>
        /// The date and time at which this Customer was activated.
        /// </summary>
        [JsonProperty("activated_at")]
        public DateTime? ActivatedAt { get; set; }

        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The type of Customer.
        /// </summary>
        [JsonProperty("customer_type")]
        public DeleteCustomerCustomerType? CustomerType { get; set; }

        /// <summary>
        /// Email of the Customer.
        /// </summary>
        [JsonProperty("email")]
        public string? Email { get; set; }

        /// <summary>
        /// Indicates whether or not the client is responsible for identity verification of this Customer. If true, the `kyc_status` will be "pre_verified".
        /// </summary>
        [JsonProperty("client_verified")]
        public bool? ClientVerified { get; set; }

        /// <summary>
        /// A value indicating the state of KYC/AML evaluation.
        /// </summary>
        [JsonProperty("kyc_status")]
        public DeleteCustomerKycStatus? KycStatus { get; set; } = null;

        /// <summary>
        /// A list of reasons for the current `kyc_status`.
        /// </summary>
        [JsonProperty("kyc_status_reasons")]
        public List<DeleteCustomerKycStatusReason>? KycStatusReasons { get; set; } = null;

        /// <summary>
        /// The lock reason provided by the Client, an admin User, or the system at the time the Customer was locked. This field will be null if and only if the `locked_at` is null.
        /// </summary>
        [JsonProperty("lock_reason")]
        public string? LockReason { get; set; } = null;

        /// <summary>
        /// The date and time when the Customer was locked. This field will be null if and only if the `lock_reason` is null.
        /// </summary>
        [JsonProperty("locked_at")]
        public DateTime? LockedAt { get; set; } = null;

        /// <summary>
        /// The date and time when the Customer's PII was last confirmed to be accurate.
        /// </summary>
        [JsonProperty("pii_confirmed_at")]
        public DateTime? PiiConfirmedAt { get; set; }

        /// <summary>
        /// A list of uids referring to Pools belonging to this Customer.
        /// </summary>
        [JsonProperty("pool_uids")]
        public List<string>? PoolUids { get; set; }

        /// <summary>
        /// The UID of the primary Customer. Null unless the customer type is `secondary`.
        /// </summary>
        [JsonProperty("primary_customer_uid")]
        public string? PrimaryCustomerUid { get; set; } = null;

        /// <summary>
        /// A list of Profile Responses submitted by the Customer.
        /// </summary>
        [JsonProperty("profile_responses")]
        public List<DeleteCustomerProfileResponse>? ProfileResponses { get; set; }

        /// <summary>
        /// A UID referring to the program this customer belongs to.
        /// </summary>
        [JsonProperty("program_uid")]
        public string? ProgramUid { get; set; }

        /// <summary>
        /// The UIDs of secondary Customers. Null unless the customer type is `primary`.
        /// </summary>
        [JsonProperty("secondary_customer_uids")]
        public List<string>? SecondaryCustomerUids { get; set; } = null;

        /// <summary>
        /// A value indicating the overall state of this Customer.
        /// </summary>
        [JsonProperty("status")]
        public DeleteCustomerStatus? Status { get; set; }

        /// <summary>
        /// Total asset owned by the customer in US dollars.
        /// </summary>
        [JsonProperty("total_balance")]
        public string? TotalBalance { get; set; }

        /// <summary>
        /// If the Customer's status is `archived` this will have the time at which they were archived.
        /// </summary>
        [JsonProperty("archived_at")]
        public DateTime? ArchivedAt { get; set; } = null;

        [JsonProperty("details")]
        public DeleteCustomerDetails? Details { get; set; }
    }
}