//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A value indicating the overall state of this Customer.
    /// </summary>
    public enum DeleteCustomerStatus
    {
        [JsonProperty("initiated")] Initiated,
        [JsonProperty("queued")] Queued,
        [JsonProperty("identity_verified")] IdentityVerified,
        [JsonProperty("active")] Active,
        [JsonProperty("manual_review")] ManualReview,
        [JsonProperty("rejected")] Rejected,
        [JsonProperty("pending_archival")] PendingArchival,
        [JsonProperty("archived")] Archived,
        [JsonProperty("under_review")] UnderReview,
    }

    public static class DeleteCustomerStatusExtension
    {
        public static string Value(this DeleteCustomerStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static DeleteCustomerStatus ToEnum(this string value)
        {
            foreach (var field in typeof(DeleteCustomerStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is DeleteCustomerStatus)
                    {
                        return (DeleteCustomerStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum DeleteCustomerStatus");
        }
    }
}