//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A single Combined Transfer is returned.
    /// </summary>
    public class GetCombinedTransfersUidResponseBody
    {
        /// <summary>
        /// Timestamp of when the combined_transfer was created.
        /// </summary>
        [JsonProperty("created_at")]
        public string? CreatedAt { get; set; }

        /// <summary>
        /// A collection of errors that occured during synthetic account and/or transfer creation. Only displayed if errors were detected.
        /// </summary>
        [JsonProperty("errors")]
        public List<GetCombinedTransfersUidError>? Errors { get; set; }

        /// <summary>
        /// Optional client-supplied uid.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; }

        /// <summary>
        /// The combined transfer's status.
        /// </summary>
        [JsonProperty("status")]
        public GetCombinedTransfersUidStatus? Status { get; set; }

        /// <summary>
        /// Parameters provided at time of creation. UID field will get populated once synthetic account has been successfully created, unless uid value was supplied at creation time.
        /// </summary>
        [JsonProperty("synthetic_account")]
        public GetCombinedTransfersUidSyntheticAccount? SyntheticAccount { get; set; }

        /// <summary>
        /// Parameters provided at time of creation. UID field will get populated once transfer has been successfully initiated.
        /// </summary>
        [JsonProperty("transfer")]
        public GetCombinedTransfersUidTransfer? Transfer { get; set; }

        /// <summary>
        /// Unique identifier for the Combined Transfer.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }
    }
}