//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A single Customer Product is returned.
    /// </summary>
    public class GetCustomerProductResponseBody
    {
        /// <summary>
        /// A unique identifier for this resource.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        /// <summary>
        /// the status of the Customer Product onboarding.
        /// </summary>
        [JsonProperty("status")]
        public GetCustomerProductStatus? Status { get; set; }

        /// <summary>
        /// A unique identifier for a Customer.
        /// </summary>
        [JsonProperty("customer_uid")]
        public string? CustomerUid { get; set; }

        /// <summary>
        /// The Customer's email address.
        /// </summary>
        [JsonProperty("customer_email")]
        public string? CustomerEmail { get; set; }

        /// <summary>
        /// A unique identifier for a Product.
        /// </summary>
        [JsonProperty("product_uid")]
        public string? ProductUid { get; set; }

        /// <summary>
        /// The name of the Product.
        /// </summary>
        [JsonProperty("product_name")]
        public string? ProductName { get; set; }

        /// <summary>
        /// A unique identifier for a Program.
        /// </summary>
        [JsonProperty("program_uid")]
        public string? ProgramUid { get; set; }

        /// <summary>
        /// The date and time at which the Customer Product became active.
        /// </summary>
        [JsonProperty("activated_at")]
        public DateTime? ActivatedAt { get; set; }
    }
}