//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Components;
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class GetSyntheticAccountTypeResponse
    {
        [JsonProperty("-")]
        public HTTPMetadata HttpMeta { get; set; } = default!;

        /// <summary>
        /// A single Synthetic Account Type is returned.
        /// </summary>
        public GetSyntheticAccountTypeResponseBody? Object { get; set; }

        public Dictionary<string, List<string>> Headers { get; set; } = new Dictionary<string, List<string>>();
    }
}