//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// The name of the Synthetic Account Category for this type. Accounts can be in one of several categories that indicate their handling properties and defining characteristics such as 'general' or 'external'. As an example, 'external' accounts do not actually hold any assets and are instead used to represent an account at an external institution for use in initiating transfers.
    /// </summary>
    public enum GetSyntheticAccountTypeSyntheticAccountCategory
    {
        [JsonProperty("general")] General,
        [JsonProperty("ach_external")] AchExternal,
        [JsonProperty("instant_payment_external")] InstantPaymentExternal,
        [JsonProperty("wire_external")] WireExternal,
    }

    public static class GetSyntheticAccountTypeSyntheticAccountCategoryExtension
    {
        public static string Value(this GetSyntheticAccountTypeSyntheticAccountCategory value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetSyntheticAccountTypeSyntheticAccountCategory ToEnum(this string value)
        {
            foreach (var field in typeof(GetSyntheticAccountTypeSyntheticAccountCategory).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetSyntheticAccountTypeSyntheticAccountCategory)
                    {
                        return (GetSyntheticAccountTypeSyntheticAccountCategory)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetSyntheticAccountTypeSyntheticAccountCategory");
        }
    }
}