//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A single Synthetic Account Closing Balance is returned.
    /// </summary>
    public class GetSyntheticAccountClosingBalanceResponseBody
    {
        /// <summary>
        /// Newline-generated unique id resource specific to the current endpoint.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        /// <summary>
        /// A unique id referring to the Synthetic Account.
        /// </summary>
        [JsonProperty("synthetic_account_uid")]
        public string? SyntheticAccountUid { get; set; }

        /// <summary>
        /// A unique id referring to the External Synthetic Account.
        /// </summary>
        [JsonProperty("synthetic_account_external_uid")]
        public string? SyntheticAccountExternalUid { get; set; }

        /// <summary>
        /// The USD amount of the Synthetic Account's closing balance.
        /// </summary>
        [JsonProperty("net_usd_closing_balance")]
        public string? NetUsdClosingBalance { get; set; }

        [JsonProperty("net_usd_closing_balance_as_of")]
        public DateOnly? NetUsdClosingBalanceAsOf { get; set; }
    }
}