//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A single Synthetic Line Item is returned.
    /// </summary>
    public class GetSyntheticLineItemsUidResponseBody
    {
        /// <summary>
        /// Newline-generated unique id resource specific to the current endpoint.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        /// <summary>
        /// A unique index that indicates the order in which the Synthetic Line Items were settled.
        /// </summary>
        [JsonProperty("settled_index")]
        public long? SettledIndex { get; set; }

        /// <summary>
        /// UID of the Transaction this Synthetic Line Item belongs to.
        /// </summary>
        [JsonProperty("transaction_uid")]
        public string? TransactionUid { get; set; }

        /// <summary>
        /// UID of the Synthetic Account this Synthetic Line Item is associated with.
        /// </summary>
        [JsonProperty("synthetic_account_uid")]
        public string? SyntheticAccountUid { get; set; }

        /// <summary>
        /// Other statuses such as `pending` will be available later.
        /// </summary>
        [JsonProperty("status")]
        public GetSyntheticLineItemsUidStatus? Status { get; set; }

        /// <summary>
        /// The signed USD amount of this specific Synthetic Line Item.
        /// </summary>
        [JsonProperty("us_dollar_amount")]
        public string? UsDollarAmount { get; set; }

        /// <summary>
        /// The running balance after settlement for this specific Asset Type held within the Synthetic Account, expressed in US Dollars calculated using the asset price used for settlement.
        /// </summary>
        [JsonProperty("running_us_dollar_balance")]
        public string? RunningUsDollarBalance { get; set; }

        /// <summary>
        /// The running balance after settlement for this specific Asset Type held within the Synthetic Account, expressed in units of the given asset type.
        /// </summary>
        [JsonProperty("running_asset_balance")]
        public string? RunningAssetBalance { get; set; }

        /// <summary>
        /// The quantity of the specific asset type for this Synthetic Line Item.
        /// </summary>
        [JsonProperty("asset_quantity")]
        public string? AssetQuantity { get; set; }

        /// <summary>
        /// The type of asset for this Synthetic Line Item.
        /// </summary>
        [JsonProperty("asset_type")]
        public string? AssetType { get; set; }

        /// <summary>
        /// If this Synthetic Line Item involves a security purchase/sale the USD value at the time of the purchase/sale.
        /// </summary>
        [JsonProperty("closing_price")]
        public string? ClosingPrice { get; set; }

        /// <summary>
        /// The name of the Custodial Account associated with this Synthetic Line Item.
        /// </summary>
        [JsonProperty("custodial_account_name")]
        public string? CustodialAccountName { get; set; }

        /// <summary>
        /// The UID of the Custodial Account associated with this Synthetic Line Item.
        /// </summary>
        [JsonProperty("custodial_account_uid")]
        public string? CustodialAccountUid { get; set; }

        /// <summary>
        /// Human-readable description in context of Synthetic Accounts.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// The date and time when the Synthetic Line Item is first recognized by Newline. This may be when the Transfer is initiated if the Synthetic Line Item is associated with one.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The date and time when the Synthetic Line Item is settled.
        /// </summary>
        [JsonProperty("settled_at")]
        public DateTime? SettledAt { get; set; }
    }
}