//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Filter by status. Multiple values are allowed, e.g. `status[]=begun&amp;status[]=in_progress`.
    /// </summary>
    public enum GetSyntheticLineItemsQueryParamStatus
    {
        [JsonProperty("begun")] Begun,
        [JsonProperty("failed")] Failed,
        [JsonProperty("in_progress")] InProgress,
        [JsonProperty("settled")] Settled,
    }

    public static class GetSyntheticLineItemsQueryParamStatusExtension
    {
        public static string Value(this GetSyntheticLineItemsQueryParamStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetSyntheticLineItemsQueryParamStatus ToEnum(this string value)
        {
            foreach (var field in typeof(GetSyntheticLineItemsQueryParamStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetSyntheticLineItemsQueryParamStatus)
                    {
                        return (GetSyntheticLineItemsQueryParamStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetSyntheticLineItemsQueryParamStatus");
        }
    }
}