//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// A single Transaction is returned.
    /// </summary>
    public class GetTransactionsUidResponseBody
    {
        /// <summary>
        /// Newline-generated unique id resource specific to the current endpoint.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        /// <summary>
        /// An index, distinct from a Transaction's uid, that indicates the order in which the Transactions were created.
        /// </summary>
        [JsonProperty("id")]
        public long? Id { get; set; }

        /// <summary>
        /// The UID of the Adjustment this Transaction is associated with, if any.
        /// </summary>
        [JsonProperty("adjustment_uid")]
        public string? AdjustmentUid { get; set; } = null;

        /// <summary>
        /// The unique id of the Customer associated with the Transaction.
        /// </summary>
        [JsonProperty("customer_uid")]
        public string? CustomerUid { get; set; }

        /// <summary>
        /// The date and time when the Transaction is first recognized by Newline. This may be when the Transfer is initiated if the Transaction is associated with one.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// A list of unique ids referring to Custodial Accounts that are currently involved in this Transaction. An empty array will be returned if there are no Custodial Accounts involved. The array may contain more values as the Transaction progresses and will no longer grow when its status becomes settled. The array may still be empty by the time the Transaction is settled if there is no custodial asset movement as a result of this Transaction.
        /// </summary>
        [JsonProperty("custodial_account_uids")]
        public List<string>? CustodialAccountUids { get; set; }

        /// <summary>
        /// Description provided to the Transaction during origination.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Synthetic Account where the asset has landed.
        /// </summary>
        [JsonProperty("destination_synthetic_account_uid")]
        public string? DestinationSyntheticAccountUid { get; set; }

        /// <summary>
        /// The date and time of some action (e.g. a debit authorization) that resulted in this Transaction's creation. When relevant and available, this value is a timestamp received by and generated externally to Newline; otherwise, this value will be when a transaction request was received and virtually identical to `created_at`
        /// </summary>
        [JsonProperty("initial_action_at")]
        public DateTime? InitialActionAt { get; set; }

        /// <summary>
        /// Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction.
        /// </summary>
        [JsonProperty("net_asset")]
        public GetTransactionsUidNetAsset? NetAsset { get; set; }

        /// <summary>
        /// The uid of a related Return, when applicable.
        /// </summary>
        [JsonProperty("return_uid")]
        public string? ReturnUid { get; set; } = null;

        /// <summary>
        /// The date and time when the Transaction is settled.
        /// </summary>
        [JsonProperty("settled_at")]
        public DateTime? SettledAt { get; set; }

        /// <summary>
        /// Another unique index that indicates the order in which the Transactions were settled. Null if the Transaction's status is queued or pending.
        /// </summary>
        [JsonProperty("settled_index")]
        public long? SettledIndex { get; set; } = null;

        /// <summary>
        /// Synthetic Account from where the asset is pulled.
        /// </summary>
        [JsonProperty("source_synthetic_account_uid")]
        public string? SourceSyntheticAccountUid { get; set; }

        /// <summary>
        /// The date and time when the statement was posted.
        /// </summary>
        [JsonProperty("statement_posted_at")]
        public DateTime? StatementPostedAt { get; set; } = null;

        /// <summary>
        /// When a Transfer is created via <a href="/reference/post_transfers">POST /transfers</a>, an associated Transaction is created with status `queued`. If it involves at least one custodial transfer, once the custodial transfer is initiated, the status will transition to `pending`.<br/>
        /// <br/>
        /// Once a Transaction is settled, whether it has asset movement in custodial level, or is synthetic-only, or is RDFI (Receiving Depository Financial Institution, meaning no Newline Transfer was associated), it will have a `settled` status.
        /// </summary>
        [JsonProperty("status")]
        public GetTransactionsUidStatus? Status { get; set; }

        /// <summary>
        /// The unique id of the Transaction Batch this Transaction is associated with, if any.
        /// </summary>
        [JsonProperty("transaction_batch_uid")]
        public string? TransactionBatchUid { get; set; } = null;

        /// <summary>
        /// A list of unique ids referring to Transaction Events belonging to this Transaction. An empty array will be returned if there is no event involved. The array may contain more values as the Transaction progresses and will no longer grow when its status becomes settled. The array may still be empty at the time the Transaction is settled if there is no custodial asset movement as a result of this Transaction.
        /// </summary>
        [JsonProperty("transaction_event_uids")]
        public List<string>? TransactionEventUids { get; set; }

        /// <summary>
        /// The unique id of the Transfer this Transaction is associated with, if any.
        /// </summary>
        [JsonProperty("transfer_uid")]
        public string? TransferUid { get; set; } = null;

        /// <summary>
        /// Transactions are categorized by Type.  See the Transaction Statuses and Transaction Types section below for a list and definition of each Transaction Type that Newline supports.
        /// </summary>
        [JsonProperty("type")]
        public GetTransactionsUidType? Type { get; set; }

        /// <summary>
        /// The amount of the Transaction in question. The amount will never be negative, please refer to the net_asset field for direction (i.e., credit or debit).
        /// </summary>
        [JsonProperty("us_dollar_amount")]
        public string? UsDollarAmount { get; set; }

        /// <summary>
        /// The VRN uid, when the transaction was processed using a VRN.
        /// </summary>
        [JsonProperty("virtual_reference_number_uid")]
        public string? VirtualReferenceNumberUid { get; set; }

        /// <summary>
        /// Transaction Authorization information. Only present if authorization was required for a given transaction.
        /// </summary>
        [JsonProperty("authorization")]
        public GetTransactionsUidAuthorization? Authorization { get; set; }

        /// <summary>
        /// Instant payment information. Only present if the Transaction is an instant payment.
        /// </summary>
        [JsonProperty("instant_payment")]
        public GetTransactionsUidInstantPayment? InstantPayment { get; set; }

        /// <summary>
        /// Wire-specific information. Only present if the Transaction is a wire.
        /// </summary>
        [JsonProperty("wire")]
        public GetTransactionsUidWire? Wire { get; set; }

        /// <summary>
        /// ACH-specific information. Only present if the Transaction is an ACH. The optional `iat` object within `ach` contains details for International ACH Transactions. It is only included if `iat_ach_display_enabled` is set to `true` for the program and the transaction contains IAT data.
        /// </summary>
        [JsonProperty("ach")]
        public GetTransactionsUidAch? Ach { get; set; }
    }
}