//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Name and address of the Transmitter.
    /// </summary>
    public class GetTransactionsInstantPaymentTransmitter
    {
        /// <summary>
        /// Name of the Transmitter.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Building number for Transmitter address. Alphanumeric only.
        /// </summary>
        [JsonProperty("street_number")]
        public string StreetNumber { get; set; } = default!;

        /// <summary>
        /// Street name for Transmitter address.
        /// </summary>
        [JsonProperty("street1")]
        public string Street1 { get; set; } = default!;

        /// <summary>
        /// Maximum 35 characters.
        /// </summary>
        [JsonProperty("city", NullValueHandling = NullValueHandling.Include)]
        public string? City { get; set; }

        /// <summary>
        /// 2 characters. Must be a valid US state abbreviation.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Include)]
        public string? State { get; set; }

        /// <summary>
        /// 5-digit string. ZIP+4 is allowed.
        /// </summary>
        [JsonProperty("postal_code", NullValueHandling = NullValueHandling.Include)]
        public string? PostalCode { get; set; }

        [JsonProperty("country", NullValueHandling = NullValueHandling.Include)]
        public string? Country { get; set; }
    }
}