//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// When a Transfer is created via <a href="/reference/post_transfers">POST /transfers</a>, an associated Transaction is created with status `queued`. If it involves at least one custodial transfer, once the custodial transfer is initiated, the status will transition to `pending`.<br/>
    /// <br/>
    /// Once a Transaction is settled, whether it has asset movement in custodial level, or is synthetic-only, or is RDFI (Receiving Depository Financial Institution, meaning no Newline Transfer was associated), it will have a `settled` status.
    /// </summary>
    public enum GetTransactionsDataStatus
    {
        [JsonProperty("canceled")] Canceled,
        [JsonProperty("queued")] Queued,
        [JsonProperty("pending")] Pending,
        [JsonProperty("settled")] Settled,
        [JsonProperty("failed")] Failed,
        [JsonProperty("denied")] Denied,
        [JsonProperty("expired")] Expired,
    }

    public static class GetTransactionsDataStatusExtension
    {
        public static string Value(this GetTransactionsDataStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTransactionsDataStatus ToEnum(this string value)
        {
            foreach (var field in typeof(GetTransactionsDataStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTransactionsDataStatus)
                    {
                        return (GetTransactionsDataStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTransactionsDataStatus");
        }
    }
}