//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Indicates whether the Customer's asset has gone up (`positive`), gone down (`negative`) or stayed the same (`neutral`) as a result of this Transaction.
    /// </summary>
    public enum GetTransactionsUidNetAsset
    {
        [JsonProperty("positive")] Positive,
        [JsonProperty("negative")] Negative,
        [JsonProperty("neutral")] Neutral,
    }

    public static class GetTransactionsUidNetAssetExtension
    {
        public static string Value(this GetTransactionsUidNetAsset value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTransactionsUidNetAsset ToEnum(this string value)
        {
            foreach (var field in typeof(GetTransactionsUidNetAsset).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTransactionsUidNetAsset)
                    {
                        return (GetTransactionsUidNetAsset)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTransactionsUidNetAsset");
        }
    }
}