//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    public enum GetTransactionEventsTypeSettled
    {
        [JsonProperty("odfi_ach_deposit")] OdfiAchDeposit,
        [JsonProperty("odfi_ach_withdrawal")] OdfiAchWithdrawal,
        [JsonProperty("rdfi_ach_deposit")] RdfiAchDeposit,
        [JsonProperty("rdfi_ach_withdrawal")] RdfiAchWithdrawal,
    }

    public static class GetTransactionEventsTypeSettledExtension
    {
        public static string Value(this GetTransactionEventsTypeSettled value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTransactionEventsTypeSettled ToEnum(this string value)
        {
            foreach (var field in typeof(GetTransactionEventsTypeSettled).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTransactionEventsTypeSettled)
                    {
                        return (GetTransactionEventsTypeSettled)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTransactionEventsTypeSettled");
        }
    }
}