//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// International ACH Transaction (IAT) details.
    /// </summary>
    public class GetTransactionsIat
    {
        /// <summary>
        /// Identifies if the currency of the transaction changes.<br/>
        /// The Newline API supports the following values:<br/>
        /// <br/>
        /// - `FF` - Fixed to Fixed<br/>
        /// - `FV` - Fixed to Variable.
        /// </summary>
        [JsonProperty("foreign_exchange_indicator")]
        public string? ForeignExchangeIndicator { get; set; }

        /// <summary>
        /// Defines the type of value in the "foreign_exchange_reference" field.<br/>
        /// The Newline API supports the following values:<br/>
        /// <br/>
        /// - `"1"` - Foreign Exchange Rate<br/>
        /// - `"2"` - Foreign Exchange Reference Number<br/>
        /// - `"3"` - If Foreign Exchange Indicator is "FF"
        /// </summary>
        [JsonProperty("foreign_exchange_reference_indicator")]
        public string? ForeignExchangeReferenceIndicator { get; set; }

        /// <summary>
        /// If "foreign_exchange_indicator" is "FF" then this field blank;  otherwise it will contain either the foreign exchange rate used to execute the foreign exchange conversion  or another reference to the foreign exchange transaction.
        /// </summary>
        [JsonProperty("foreign_exchange_reference")]
        public string? ForeignExchangeReference { get; set; }

        /// <summary>
        /// Country code of the destination country.
        /// </summary>
        [JsonProperty("iso_destination_country_code")]
        public string? IsoDestinationCountryCode { get; set; }

        /// <summary>
        /// Currency code for transaction origination currency.
        /// </summary>
        [JsonProperty("iso_originating_currency_code")]
        public string? IsoOriginatingCurrencyCode { get; set; }

        /// <summary>
        /// Currency code for transaction destination currency.
        /// </summary>
        [JsonProperty("iso_destination_currency_code")]
        public string? IsoDestinationCurrencyCode { get; set; }

        /// <summary>
        /// Transaction code describing a debit or credit and the account type used in the payment.<br/>
        /// Payment transaction code requirements differ based on the receiving country.
        /// </summary>
        [JsonProperty("transaction_code")]
        public string? TransactionCode { get; set; }

        /// <summary>
        /// Identifies the IAT Transaction Type Code.<br/>
        /// The Newline API supports the following values:<br/>
        /// <br/>
        /// - `"ANN"` (Annuity)<br/>
        /// - `"RLS"` (Rent/Lease)<br/>
        /// - `"POS"` (Point of Sale Entry)<br/>
        /// - `"BUS"` (Business/Commercial)<br/>
        /// - `"SAL"` (Salary/Payroll)<br/>
        /// - `"RCK"` (Re-presented Check Entry)<br/>
        /// - `"DEP"` (Deposit)<br/>
        /// - `"TAX"` (Tax)<br/>
        /// - `"SHR"` (Shared Network Transaction)<br/>
        /// - `"LOA"` (Loan)<br/>
        /// - `"TEL"` (Telephone-Initiated Entry)<br/>
        /// - `"MIS"` (Miscellaneous)<br/>
        /// - `"ARC"` (Accounts Receivable Entry)<br/>
        /// - `"WEB"` (Internet-Initiated Entry)<br/>
        /// - `"MOR"` (Mortgage)<br/>
        /// - `"BOC"` (Back Office Conversion Entry)<br/>
        /// - `"PEN"` (Pension)<br/>
        /// - `"MTE"` (Machine Transfer Entry)<br/>
        /// - `"REM"` (Remittance)<br/>
        /// - `"POP"` (Point of Purchase Entry).
        /// </summary>
        [JsonProperty("transaction_type_code")]
        public string? TransactionTypeCode { get; set; }

        /// <summary>
        /// The value of the funds if the destination currency code is different from destination country code.
        /// </summary>
        [JsonProperty("foreign_payment_amount")]
        public string? ForeignPaymentAmount { get; set; }

        /// <summary>
        /// Optional trace number that can be supplied by the originator.
        /// </summary>
        [JsonProperty("foreign_trace_number")]
        public string? ForeignTraceNumber { get; set; }

        /// <summary>
        /// The street address of the originator. On received IATs, <br/>
        /// this is the originator's street address supplied with the received payment.
        /// </summary>
        [JsonProperty("originator_street_address")]
        public string? OriginatorStreetAddress { get; set; }

        /// <summary>
        /// The city and, if applicable, the state or province of the Originator. <br/>
        /// An asterisk (*) will separate the two values in this field.
        /// </summary>
        [JsonProperty("originator_city_state_province")]
        public string? OriginatorCityStateProvince { get; set; }

        /// <summary>
        /// The two-character alphabetic country code, as defined within the ISO 3166-1-alpha-2 code list, <br/>
        /// and the postal code of the Originator. An asterisk (*) will separate the two values in this field.
        /// </summary>
        [JsonProperty("originator_country_postal_code")]
        public string? OriginatorCountryPostalCode { get; set; }

        /// <summary>
        /// The name of the ODFI.
        /// </summary>
        [JsonProperty("odfi_name")]
        public string? OdfiName { get; set; }

        /// <summary>
        /// A 2-digit code that identifies the type of ID in the "odfi_id" field.<br/>
        /// The Newline API supports the following values:<br/>
        /// <br/>
        /// - `"01"` - National Clearing System Number<br/>
        /// - `"02"` - BIC Code<br/>
        /// - `"03"` - IBAN.
        /// </summary>
        [JsonProperty("odfi_identification_number_qualifier")]
        public string? OdfiIdentificationNumberQualifier { get; set; }

        /// <summary>
        /// The bank identification number of the DFI at which the Originator maintains their account.
        /// </summary>
        [JsonProperty("odfi_id")]
        public string? OdfiId { get; set; }

        /// <summary>
        /// Country code of the ODFI.
        /// </summary>
        [JsonProperty("odfi_branch_country_code")]
        public string? OdfiBranchCountryCode { get; set; }

        /// <summary>
        /// The name of the RDFI.
        /// </summary>
        [JsonProperty("rdfi_name")]
        public string? RdfiName { get; set; }

        /// <summary>
        /// A 2-digit code that identifies the type of ID in the "rdfi_id" field.<br/>
        /// The Newline API supports the following values:<br/>
        /// <br/>
        /// - `"01"` - National Clearing System Number<br/>
        /// - `"02"` - BIC Code<br/>
        /// - `"03"` - IBAN.
        /// </summary>
        [JsonProperty("rdfi_identification_number_qualifier")]
        public string? RdfiIdentificationNumberQualifier { get; set; }

        /// <summary>
        /// The bank identification number of the DFI at which the Receiver maintains his account.
        /// </summary>
        [JsonProperty("rdfi_id")]
        public string? RdfiId { get; set; }

        /// <summary>
        /// Country code of the RDFI. Will always be US for domestic IAT transactions.
        /// </summary>
        [JsonProperty("rdfi_branch_country_code")]
        public string? RdfiBranchCountryCode { get; set; }

        /// <summary>
        /// The street address of the Receiver.
        /// </summary>
        [JsonProperty("counterparty_street_address")]
        public string? CounterpartyStreetAddress { get; set; }

        /// <summary>
        /// The city and, if applicable, the state or province of the Receiver. <br/>
        /// An asterisk (*) will separate the two values in this field.
        /// </summary>
        [JsonProperty("counterparty_city_state_province")]
        public string? CounterpartyCityStateProvince { get; set; }

        /// <summary>
        /// The two-character alphabetic country code, as defined within the ISO 3166-1-alpha-2 code list, <br/>
        /// and the postal code of the Receiver. An asterisk (*) will separate the two values in this field.
        /// </summary>
        [JsonProperty("counterparty_country_postal_code")]
        public string? CounterpartyCountryPostalCode { get; set; }

        /// <summary>
        /// The payment related information found in the remitance information addenda when provided. <br/>
        /// When the payment related information for an IAT Entry includes the identification of a country, <br/>
        /// that country must be identified using that country's two-character alphabetic country code, <br/>
        /// as defined within the ISO 3166-1-alpha-2 code list.<br/>
        /// <br/>
        /// An asterisk ("*") will be used as the delimiter between the data elements in the field.
        /// </summary>
        [JsonProperty("payment_related_information_1")]
        public string? PaymentRelatedInformation1 { get; set; }

        /// <summary>
        /// The payment related information found in the remitance information addenda when provided. <br/>
        /// When the payment related information for an IAT Entry includes the identification of a country, <br/>
        /// that country must be identified using that country's two-character alphabetic country code, <br/>
        /// as defined within the ISO 3166-1-alpha-2 code list.<br/>
        /// <br/>
        /// An asterisk ("*") will be used as the delimiter between the data elements in the field.
        /// </summary>
        [JsonProperty("payment_related_information_2")]
        public string? PaymentRelatedInformation2 { get; set; }

        /// <summary>
        /// List of foreign correspondent banks involved in the IAT transaction.
        /// </summary>
        [JsonProperty("foreign_correspondent_banks")]
        public List<GetTransactionsForeignCorrespondentBank>? ForeignCorrespondentBanks { get; set; }
    }
}