//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Instant payment information. Only present if the Transaction is an instant payment.
    /// </summary>
    public class GetTransactionsInstantPayment
    {
        /// <summary>
        /// For newline initiated instant payments, a unique newline trace ID assigned to the transaction. For externally initiated instant payments, a unique transaction ID assigned by the network facilitating the instant payment.
        /// </summary>
        [JsonProperty("network_transaction_id")]
        public string? NetworkTransactionId { get; set; }

        /// <summary>
        /// The network on which the instant payment was executed.
        /// </summary>
        [JsonProperty("network")]
        public string? Network { get; set; }

        /// <summary>
        /// A code indicating failure reason. It will only appear if transaction status is `failed`
        /// </summary>
        [JsonProperty("failure_code")]
        public string? FailureCode { get; set; }

        /// <summary>
        /// A description of why the transaction failed. It will only appear if transaction status is `failed`
        /// </summary>
        [JsonProperty("failure_reason")]
        public string? FailureReason { get; set; }

        /// <summary>
        /// Name of the business or individual who owns the counterparty Account.
        /// </summary>
        [JsonProperty("counterparty_name")]
        public string? CounterpartyName { get; set; }

        /// <summary>
        /// Name of the financial institution where the counterparty account is held.
        /// </summary>
        [JsonProperty("counterparty_bank_name")]
        public string? CounterpartyBankName { get; set; }

        /// <summary>
        /// The routing number associated with the counterparty bank account.
        /// </summary>
        [JsonProperty("counterparty_bank_routing_number")]
        public string? CounterpartyBankRoutingNumber { get; set; }

        /// <summary>
        /// Last four digits of counterparty account number.
        /// </summary>
        [JsonProperty("counterparty_account_number_last_four")]
        public string? CounterpartyAccountNumberLastFour { get; set; }

        /// <summary>
        /// An originator-defined value. For RTP transactions, this will be the End-to-End ID.
        /// </summary>
        [JsonProperty("payment_id")]
        public string? PaymentId { get; set; }

        /// <summary>
        /// An optional code supplied when an instant payment Transfer is initiated, indicating the kind of transaction being sent. If supplied, it must be one of the approved codes listed below, otherwise the Transfer is rejected. Omit the field or send an empty string to leave it unset; when unset it is returned as an empty string. Only applies to Newline initiated instant payments; it is not populated for received instant payments.
        /// </summary>
        [JsonProperty("purpose_of_payment")]
        public GetTransactionsPurposeOfPayment? PurposeOfPayment { get; set; } = null;

        /// <summary>
        /// This field is currently always null.
        /// </summary>
        [JsonProperty("original_end_to_end_id")]
        public string? OriginalEndToEndId { get; set; } = null;

        /// <summary>
        /// Name of the initiating counterparty. Deprecated in favor of `initiating_party_name`.
        /// </summary>
        [JsonProperty("transmitter_name")]
        public string? TransmitterName { get; set; }

        /// <summary>
        /// Name of the initiating counterparty.
        /// </summary>
        [JsonProperty("initiating_party_name")]
        public string? InitiatingPartyName { get; set; }

        /// <summary>
        /// Name and address of the Transmitter.
        /// </summary>
        [JsonProperty("instant_payment_transmitter")]
        public GetTransactionsInstantPaymentTransmitter? InstantPaymentTransmitter { get; set; }

        /// <summary>
        /// Address of the financial institution where the external account is held.
        /// </summary>
        [JsonProperty("counterparty_bank_address")]
        public GetTransactionsCounterpartyBankAddress? CounterpartyBankAddress { get; set; } = null;
    }
}