//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Transactions are categorized by Type.  See the Transaction Statuses and Transaction Types section below for a list and definition of each Transaction Type that Newline supports.
    /// </summary>
    public enum GetTransactionsUidType
    {
        [JsonProperty("ach")] Ach,
        [JsonProperty("ach_return")] AchReturn,
        [JsonProperty("atm_withdrawal")] AtmWithdrawal,
        [JsonProperty("book_transfer")] BookTransfer,
        [JsonProperty("card_load")] CardLoad,
        [JsonProperty("card_purchase")] CardPurchase,
        [JsonProperty("card_refund")] CardRefund,
        [JsonProperty("cash_load")] CashLoad,
        [JsonProperty("corporate_action")] CorporateAction,
        [JsonProperty("credit")] Credit,
        [JsonProperty("denied_authorization")] DeniedAuthorization,
        [JsonProperty("dispute")] Dispute,
        [JsonProperty("fee")] Fee,
        [JsonProperty("initiated_ach_return")] InitiatedAchReturn,
        [JsonProperty("initiated_ach_reversal")] InitiatedAchReversal,
        [JsonProperty("initiated_wire_return")] InitiatedWireReturn,
        [JsonProperty("instant_payment")] InstantPayment,
        [JsonProperty("interest")] Interest,
        [JsonProperty("other")] Other,
        [JsonProperty("peer_to_peer_transfer")] PeerToPeerTransfer,
        [JsonProperty("reversal")] Reversal,
        [JsonProperty("reversed_transfer")] ReversedTransfer,
        [JsonProperty("set_account_balance")] SetAccountBalance,
        [JsonProperty("wire")] Wire,
    }

    public static class GetTransactionsUidTypeExtension
    {
        public static string Value(this GetTransactionsUidType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTransactionsUidType ToEnum(this string value)
        {
            foreach (var field in typeof(GetTransactionsUidType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTransactionsUidType)
                    {
                        return (GetTransactionsUidType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTransactionsUidType");
        }
    }
}