//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// A value indicating the current state of authorization for this transaction.
    /// </summary>
    public enum GetTransactionsAuthorizationStatus
    {
        [JsonProperty("auto_approved")] AutoApproved,
        [JsonProperty("auto_denied")] AutoDenied,
        [JsonProperty("client_approval_pending")] ClientApprovalPending,
        [JsonProperty("client_approved")] ClientApproved,
        [JsonProperty("client_denied")] ClientDenied,
        [JsonProperty("client_unanswered_auto_approved")] ClientUnansweredAutoApproved,
        [JsonProperty("client_unanswered_auto_denied")] ClientUnansweredAutoDenied,
        [JsonProperty("created")] Created,
    }

    public static class GetTransactionsAuthorizationStatusExtension
    {
        public static string Value(this GetTransactionsAuthorizationStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetTransactionsAuthorizationStatus ToEnum(this string value)
        {
            foreach (var field in typeof(GetTransactionsAuthorizationStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetTransactionsAuthorizationStatus)
                    {
                        return (GetTransactionsAuthorizationStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetTransactionsAuthorizationStatus");
        }
    }
}