//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;

    public class GetTransactionEventsRequest
    {
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=source_custodial_account_uid")]
        public string? SourceCustodialAccountUid { get; set; }

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=destination_custodial_account_uid")]
        public string? DestinationCustodialAccountUid { get; set; }

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=custodial_account_uid")]
        public string? CustodialAccountUid { get; set; }

        /// <summary>
        /// Filter by type. Multiple values are allowed, e.g. `type[]=odfi_ach_deposit&amp;type[]=odfi_ach_withdrawal`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")]
        public GetTransactionEventsQueryParamType? Type { get; set; }

        /// <summary>
        /// Filter by Transaction. Multiple values are allowed, e.g. `transaction_uid[]=SMwKC1osz77DTEiu&amp;transaction_uid[]=f1UDvUVNnXTKtgxu`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=transaction_uid")]
        public string? TransactionUid { get; set; }

        /// <summary>
        /// Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 100;

        /// <summary>
        /// Index of the items to start retrieving from.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")]
        public long? Offset { get; set; } = 0;

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")]
        public GetTransactionEventsSort? Sort { get; set; }
    }
}