//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using System;

    public class GetTransactionsRequest
    {
        /// <summary>
        /// Filter by Customer. Multiple values are allowed, e.g. `customer_uid[]=uKxmLxUEiSj5h4M3&amp;customer_uid[]=y9reyPMNEWuuYSC1`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=customer_uid")]
        public string? CustomerUid { get; set; }

        /// <summary>
        /// Filter by pool. Multiple values are allowed, e.g. `pool_uid[]=wTSMX1GubP21ev2h&amp;pool_uid[]=7UvkHn3Ss9AbWe2c`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=pool_uid")]
        public string? PoolUid { get; set; }

        /// <summary>
        /// Filter by source Synthetic Account. Multiple values are allowed, e.g. `source_synthetic_account_uid[]=4XkJnsfHsuqrxmeX&amp;source_synthetic_account_uid[]=aeD4RMVyTKaspEzj`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=source_synthetic_account_uid")]
        public string? SourceSyntheticAccountUid { get; set; }

        /// <summary>
        /// Filter by destination Synthetic Account. Multiple values are allowed, e.g. `destination_synthetic_synthetic_uid[]=exMDShw6yM3NHLYV&amp;destination_synthetic_account_uid[]=1WVbRrp1s1MvTaAe`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=destination_synthetic_account_uid")]
        public string? DestinationSyntheticAccountUid { get; set; }

        /// <summary>
        /// Filter by Synthetic Account, source or destination. Multiple values are allowed, e.g. `synthetic_account_uid[]=4XkJnsfHsuqrxmeX&amp;synthetic_account_uid[]=exMDShw6yM3NHLYV`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=synthetic_account_uid")]
        public string? SyntheticAccountUid { get; set; }

        /// <summary>
        /// Filter by type. Multiple values are allowed, e.g. `type[]=dispute&amp;type[]=fee`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=type")]
        public GetTransactionsQueryParamType? Type { get; set; }

        /// <summary>
        /// Filter by return. Only transactions that have returns (present or absend) to be included in the results.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=has_return")]
        public bool? HasReturn { get; set; }

        /// <summary>
        /// Causes transactions with a status of `denied` (suppressed by default) to be included in the results.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=show_denied_auths")]
        public bool? ShowDeniedAuths { get; set; }

        /// <summary>
        /// Causes transactions with a status of `expired` (suppressed by default) to be included in the results.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=show_expired")]
        public bool? ShowExpired { get; set; }

        /// <summary>
        /// Filter by status. Multiple values are allowed, e.g. `status[]=queued&amp;status[]=pending`.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=status")]
        public GetTransactionsQueryParamStatus? Status { get; set; }

        /// <summary>
        /// Attempts to search for the provided string in the description field. '*' can be used as a wildcard at the beginning or end of the string. Any record with a match will be returned.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=search_description")]
        public string? SearchDescription { get; set; }

        /// <summary>
        /// Causes transactions with a `us_dollar_amount = 0` (suppressed by default) to be included in the results.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include_zero")]
        public bool? IncludeZero { get; set; }

        /// <summary>
        /// Maximum number of items to retrieve. This filter is automatically applied with the default value if not given.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 100;

        /// <summary>
        /// Index of the items to start retrieving from.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")]
        public long? Offset { get; set; } = 0;

        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=sort")]
        public GetTransactionsSort? Sort { get; set; }

        /// <summary>
        /// Return only results with `created_at` after the provided ISO 8601 date or timestamp.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=created_at_after")]
        public DateTime? CreatedAtAfter { get; set; }

        /// <summary>
        /// Return only results with `created_at` before the provided ISO 8601 date or timestamp.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=created_at_before")]
        public DateTime? CreatedAtBefore { get; set; }

        /// <summary>
        /// Return only transactions with `settled_at` after the provided ISO 8601 timestamp.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=settled_at_after")]
        public DateTime? SettledAtAfter { get; set; }

        /// <summary>
        /// Return only transactions with `settled_at` before the provided ISO 8601 timestamp.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=settled_at_before")]
        public DateTime? SettledAtBefore { get; set; }

        /// <summary>
        /// Return only transactions with `initial_action_at` after the provided ISO 8601 timestamp.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=initial_action_at_after")]
        public DateTime? InitialActionAtAfter { get; set; }

        /// <summary>
        /// Return only transactions with `initial_action_at` before the provided ISO 8601 timestamp.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=initial_action_at_before")]
        public DateTime? InitialActionAtBefore { get; set; }

        /// <summary>
        /// Return only transactions with `settled_index` after the provided value.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=settled_index_after")]
        public long? SettledIndexAfter { get; set; }

        /// <summary>
        /// Return only transactions with `settled_index` before the provided value.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=settled_index_before")]
        public long? SettledIndexBefore { get; set; }

        /// <summary>
        /// Return only transactions with `id` after the provided value.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=id_after")]
        public long? IdAfter { get; set; }

        /// <summary>
        /// Return only transactions with `id` before the provided value.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=id_before")]
        public long? IdBefore { get; set; }
    }
}