//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class ListPoolsData
    {
        /// <summary>
        /// Newline-generated unique id resource specific to the current endpoint.
        /// </summary>
        [JsonProperty("uid")]
        public string? Uid { get; set; }

        /// <summary>
        /// A unique name, per pool, to identify the resource.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        [JsonProperty("owner_customer_uid")]
        public string OwnerCustomerUid { get; set; } = default!;

        [JsonProperty("customer_uids")]
        public List<string>? CustomerUids { get; set; }
    }
}