//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;

    public class ListProductsRequest
    {
        /// <summary>
        /// Only return Products belonging to the submitted Program.
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=program_uid")]
        public string? ProgramUid { get; set; }
    }
}