//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Filter by type. Multiple values are allowed, e.g. `type[]=dda&amp;type[]=dda_cash_external`.
    /// </summary>
    public enum ListCustodialAccountsQueryParamType
    {
        [JsonProperty("dda")] Dda,
        [JsonProperty("dda_cash_external")] DdaCashExternal,
        [JsonProperty("dda_cash_received")] DdaCashReceived,
    }

    public static class ListCustodialAccountsQueryParamTypeExtension
    {
        public static string Value(this ListCustodialAccountsQueryParamType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ListCustodialAccountsQueryParamType ToEnum(this string value)
        {
            foreach (var field in typeof(ListCustodialAccountsQueryParamType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ListCustodialAccountsQueryParamType)
                    {
                        return (ListCustodialAccountsQueryParamType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ListCustodialAccountsQueryParamType");
        }
    }
}