//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    public enum ListCustomersKycStatusReason
    {
        [JsonProperty("Approved")] Approved,
        [JsonProperty("Valid Documents Provided")] ValidDocumentsProvided,
        [JsonProperty("Archived due to application inactivity")] ArchivedDueToApplicationInactivity,
        [JsonProperty("Further review required")] FurtherReviewRequired,
        [JsonProperty("Minor (age < 18 years)")] MinorAgeLessThan18Years,
        [JsonProperty("Invalid Documents submitted multiple times")] InvalidDocumentsSubmittedMultipleTimes,
        [JsonProperty("Minimum requirements to open an account were not met")] MinimumRequirementsToOpenAnAccountWereNotMet,
        [JsonProperty("Invalid documents")] InvalidDocuments,
        [JsonProperty("Incorrect document provided for ID document")] IncorrectDocumentProvidedForIDDocument,
        [JsonProperty("Expired ID")] ExpiredID,
        [JsonProperty("Illegible ID document")] IllegibleIDDocument,
        [JsonProperty("Incorrect document provided for POA document")] IncorrectDocumentProvidedForPOADocument,
        [JsonProperty("Invalid POA provided")] InvalidPOAProvided,
        [JsonProperty("Illegible POA document")] IllegiblePOADocument,
    }

    public static class ListCustomersKycStatusReasonExtension
    {
        public static string Value(this ListCustomersKycStatusReason value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ListCustomersKycStatusReason ToEnum(this string value)
        {
            foreach (var field in typeof(ListCustomersKycStatusReason).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ListCustomersKycStatusReason)
                    {
                        return (ListCustomersKycStatusReason)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ListCustomersKycStatusReason");
        }
    }
}