//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    /// <summary>
    /// A list of Custodial Accounts is returned.
    /// </summary>
    public class ListCustodialAccountsResponseBody
    {
        /// <summary>
        /// Total count of items available to retrieve.
        /// </summary>
        [JsonProperty("total_count")]
        public long? TotalCount { get; set; }

        /// <summary>
        /// Number of items retrieved.
        /// </summary>
        [JsonProperty("count")]
        public long? Count { get; set; }

        /// <summary>
        /// Maximum number of items to retrieve.
        /// </summary>
        [JsonProperty("limit")]
        public long? Limit { get; set; }

        /// <summary>
        /// Index of the first item to retrieve.
        /// </summary>
        [JsonProperty("offset")]
        public long? Offset { get; set; }

        [JsonProperty("data")]
        public List<ListCustodialAccountsData>? Data { get; set; }
    }
}