//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Requested service processing duration for the ACH transfer. Allowable values are: STANDARD or SAMEDAY.
    /// </summary>
    public enum ListTransfersServiceProcessing
    {
        [JsonProperty("SAMEDAY")] Sameday,
        [JsonProperty("STANDARD")] Standard,
    }

    public static class ListTransfersServiceProcessingExtension
    {
        public static string Value(this ListTransfersServiceProcessing value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ListTransfersServiceProcessing ToEnum(this string value)
        {
            foreach (var field in typeof(ListTransfersServiceProcessing).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ListTransfersServiceProcessing)
                    {
                        return (ListTransfersServiceProcessing)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ListTransfersServiceProcessing");
        }
    }
}