//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    public enum ListSyntheticAccountsSort
    {
        [JsonProperty("name_asc")] NameAsc,
        [JsonProperty("name_desc")] NameDesc,
        [JsonProperty("net_usd_balance_asc")] NetUsdBalanceAsc,
        [JsonProperty("net_usd_balance_desc")] NetUsdBalanceDesc,
        [JsonProperty("net_usd_pending_balance_asc")] NetUsdPendingBalanceAsc,
        [JsonProperty("net_usd_pending_balance_desc")] NetUsdPendingBalanceDesc,
        [JsonProperty("net_usd_available_balance_asc")] NetUsdAvailableBalanceAsc,
        [JsonProperty("net_usd_available_balance_desc")] NetUsdAvailableBalanceDesc,
    }

    public static class ListSyntheticAccountsSortExtension
    {
        public static string Value(this ListSyntheticAccountsSort value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ListSyntheticAccountsSort ToEnum(this string value)
        {
            foreach (var field in typeof(ListSyntheticAccountsSort).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ListSyntheticAccountsSort)
                    {
                        return (ListSyntheticAccountsSort)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ListSyntheticAccountsSort");
        }
    }
}