//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class ListCustodialAccountsAccountError
    {
        [JsonProperty("error_code")]
        public string? ErrorCode { get; set; }

        [JsonProperty("error_name")]
        public string? ErrorName { get; set; }

        [JsonProperty("error_description")]
        public string? ErrorDescription { get; set; }
    }
}