//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class OnboardCustomerProductRequest
    {
        /// <summary>
        /// A UID referring to the Customer generated by Newline.
        /// </summary>
        [JsonProperty("customer_uid")]
        public string CustomerUid { get; set; } = default!;

        /// <summary>
        /// A UID referring to the Product. Generated by Newline.
        /// </summary>
        [JsonProperty("product_uid")]
        public string ProductUid { get; set; } = default!;
    }
}