//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class PostVirtualReferenceNumbersError
    {
        /// <summary>
        /// Code provided by Newline for reference.
        /// </summary>
        [JsonProperty("code")]
        public long? Code { get; set; }

        /// <summary>
        /// Title of Error Code.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Description of Error Code.
        /// </summary>
        [JsonProperty("detail")]
        public string? Detail { get; set; }

        /// <summary>
        /// Error Timestamp.
        /// </summary>
        [JsonProperty("occurred_at")]
        public string? OccurredAt { get; set; }

        /// <summary>
        /// Included based on Error Code; Additional context to help users self-solve the error.
        /// </summary>
        [JsonProperty("extra")]
        public string? Extra { get; set; }
    }
}