//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class PostReturnsAchResponse
    {
        /// <summary>
        /// The reason an ACH payment is being returned. Required if returning an RDFI transaction. Optional if reversing an ODFI transaction.
        /// </summary>
        [JsonProperty("ach_return_code")]
        public PostReturnsAchReturnCodeResponse? AchReturnCode { get; set; }

        /// <summary>
        /// Freeform text (up to 44 characters) to attach a memo to return.
        /// </summary>
        [JsonProperty("addenda_info")]
        public string? AddendaInfo { get; set; }
    }
}