//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class PostVirtualReferenceNumbersRequest
    {
        /// <summary>
        /// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; }

        /// <summary>
        /// A unique name, per pool, to identify the resource.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// A unique id referring to the mapped, general Synthetic Account.
        /// </summary>
        [JsonProperty("synthetic_account_uid")]
        public string SyntheticAccountUid { get; set; } = default!;

        /// <summary>
        /// The ABA routing number associated with this VRN.
        /// </summary>
        [JsonProperty("routing_number")]
        public string RoutingNumber { get; set; } = default!;
    }
}