//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class PostReturnsRequest
    {
        /// <summary>
        /// Client supplied unique identifier. It must be unique within the customer. If the same value is given, no new resource will be created.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; }

        /// <summary>
        /// The transaction to be returned.
        /// </summary>
        [JsonProperty("original_transaction_uid")]
        public string OriginalTransactionUid { get; set; } = default!;

        /// <summary>
        /// The UID of the customer requesting a return.
        /// </summary>
        [JsonProperty("requesting_customer_uid")]
        public string RequestingCustomerUid { get; set; } = default!;

        /// <summary>
        /// Type of the customer requesting a return.
        /// </summary>
        [JsonProperty("requestor_type")]
        public RequestorTypeRequest RequestorType { get; set; } = default!;

        /// <summary>
        /// Freeform text (up to 140 characters) documenting the reason for return. For wire returns, this value will be sent to the other bank.
        /// </summary>
        [JsonProperty("return_reason")]
        public string ReturnReason { get; set; } = default!;

        [JsonProperty("ach")]
        public PostReturnsAchRequest? Ach { get; set; }

        [JsonProperty("wire")]
        public PostReturnsWireRequest? Wire { get; set; }
    }
}