//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// An optional code supplied when an instant payment Transfer is initiated, indicating the kind of transaction being sent. If supplied, it must be one of the approved codes listed below, otherwise the Transfer is rejected. Omit the field or send an empty string to leave it unset; when unset it is returned as an empty string. Only applies to Newline initiated instant payments; it is not populated for received instant payments.
    /// </summary>
    public enum PutTransfersUidCancelPurposeOfPayment
    {
        [JsonProperty("NOWS")] Nows,
        [JsonProperty("GDDS")] Gdds,
        [JsonProperty("SCVE")] Scve,
        [JsonProperty("INSC")] Insc,
        [JsonProperty("INSM")] Insm,
        [JsonProperty("INVS")] Invs,
        [JsonProperty("PAYR")] Payr,
        [JsonProperty("UBIL")] Ubil,
        [JsonProperty("PDEP")] Pdep,
        [JsonProperty("ACCT")] Acct,
        [JsonProperty("CBLK")] Cblk,
        [JsonProperty("MP2P")] Mp2P,
    }

    public static class PutTransfersUidCancelPurposeOfPaymentExtension
    {
        public static string Value(this PutTransfersUidCancelPurposeOfPayment value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PutTransfersUidCancelPurposeOfPayment ToEnum(this string value)
        {
            foreach (var field in typeof(PutTransfersUidCancelPurposeOfPayment).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PutTransfersUidCancelPurposeOfPayment)
                    {
                        return (PutTransfersUidCancelPurposeOfPayment)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PutTransfersUidCancelPurposeOfPayment");
        }
    }
}