//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class PutTransfersUidCancelRequestBody
    {
        /// <summary>
        /// Name of the authorized representative who wants to cancel the transfer. Max 35 characters.
        /// </summary>
        [JsonProperty("authorized_representative_name")]
        public string? AuthorizedRepresentativeName { get; set; }

        /// <summary>
        /// Reason for cancellation. Max 135 characters.
        /// </summary>
        [JsonProperty("cancellation_reason")]
        public string? CancellationReason { get; set; }
    }
}