//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The authorization resource is returned.
    /// </summary>
    public class PutTransactionsUidAuthorizeResponseBody
    {
        /// <summary>
        /// Transaction Authorization information. Only present if authorization was required for a given transaction.
        /// </summary>
        [JsonProperty("authorization")]
        public PutTransactionsUidAuthorizeAuthorization? Authorization { get; set; }
    }
}