//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Provided reason for locking the VRN.
    /// </summary>
    public enum PutVirtualReferenceNumbersUidLockLockReasonResponse
    {
        [JsonProperty("admin")] Admin,
        [JsonProperty("customer_request")] CustomerRequest,
    }

    public static class PutVirtualReferenceNumbersUidLockLockReasonResponseExtension
    {
        public static string Value(this PutVirtualReferenceNumbersUidLockLockReasonResponse value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PutVirtualReferenceNumbersUidLockLockReasonResponse ToEnum(this string value)
        {
            foreach (var field in typeof(PutVirtualReferenceNumbersUidLockLockReasonResponse).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PutVirtualReferenceNumbersUidLockLockReasonResponse)
                    {
                        return (PutVirtualReferenceNumbersUidLockLockReasonResponse)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PutVirtualReferenceNumbersUidLockLockReasonResponse");
        }
    }
}