//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// Filter by KYC status. Multiple values are allowed e.g. `kyc_status[]=approved&amp;kyc_status[]=under_review`.
    /// </summary>
    public enum QueryParamKycStatus
    {
        [JsonProperty("approved")] Approved,
        [JsonProperty("denied")] Denied,
        [JsonProperty("documents_provided")] DocumentsProvided,
        [JsonProperty("documents_rejected")] DocumentsRejected,
        [JsonProperty("manual_review")] ManualReview,
        [JsonProperty("pending_id_documents")] PendingIdDocuments,
        [JsonProperty("pending_poa_documents")] PendingPoaDocuments,
        [JsonProperty("pending_idandpoa_documents")] PendingIdandpoaDocuments,
        [JsonProperty("retake_images")] RetakeImages,
        [JsonProperty("pre_verified")] PreVerified,
    }

    public static class QueryParamKycStatusExtension
    {
        public static string Value(this QueryParamKycStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString()) [0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static QueryParamKycStatus ToEnum(this string value)
        {
            foreach (var field in typeof(QueryParamKycStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is QueryParamKycStatus)
                    {
                        return (QueryParamKycStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum QueryParamKycStatus");
        }
    }
}