//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Components;
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// Wire-specific information. Only present if the Transfer is a wire.
    /// </summary>
    public class TransferWire
    {
        /// <summary>
        /// Address of the intermediary bank. To be populated if an intermediary bank is required to execute the wire transfer.
        /// </summary>
        [JsonProperty("intermediary_bank_address")]
        public TransferIntermediaryBankAddressUnstructuredAddress? IntermediaryBankAddress { get; set; }

        [JsonProperty("intermediary_bank_name")]
        public string? IntermediaryBankName { get; set; }

        /// <summary>
        /// The ABA routing number associated with the intermediary bank involved in the wire transfer. This value is required if intermediary_bank_name or intermediary_bank_address is present; optional otherwise.
        /// </summary>
        [JsonProperty("intermediary_bank_routing_number")]
        public string? IntermediaryBankRoutingNumber { get; set; }

        /// <summary>
        /// Additional details or instructions for the wire, issued to the recipient financial institution when the wire is executed.
        /// </summary>
        [JsonProperty("wire_instructions")]
        public string? WireInstructions { get; set; }

        /// <summary>
        /// Information about the Transmitter. Must be provided if the `initiator_type` is `transmitter`. Includes the transmitter's name, identifier, and address. The accepted address format depends on your program's wire address configuration. For `unstructured` format: `line1` and `country` are required. For `structured` format: `city` and `country` are required.
        /// </summary>
        [JsonProperty("wire_transmitter", NullValueHandling = NullValueHandling.Include)]
        public PostCombinedTransfersWireTransmitter? WireTransmitter { get; set; }
    }
}