//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;

    public class UpdateSyntheticAccountRequestBody
    {
        /// <summary>
        /// A unique identifier the Client supplies. It must be unique within the resource type. If the same value is given, no new resource will be created.
        /// </summary>
        [JsonProperty("external_uid")]
        public string? ExternalUid { get; set; }

        /// <summary>
        /// A unique name, per pool, to identify the resource.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The unique id of the Synthetic Account's pool.
        /// </summary>
        [JsonProperty("pool_uid")]
        public string? PoolUid { get; set; }

        /// <summary>
        /// A unique id referring to the Synthetic Account's type.
        /// </summary>
        [JsonProperty("synthetic_account_type_uid")]
        public string? SyntheticAccountTypeUid { get; set; }

        /// <summary>
        /// The ABA routing number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require a `routing_number`. Submitting a `routing_number` with a Synthetic Account Type that does not require one will result in the routing number being ignored.
        /// </summary>
        [JsonProperty("routing_number")]
        public string? RoutingNumber { get; set; } = null;

        /// <summary>
        /// The account number (if any) associated with this account. Some Synthetic Account Types require this field to be submitted along with the POST request. For example, any Synthetic Account Type from the `ach_external` or the `wire_external` category will require an `account_number`. Submitting an `account_number` with a Synthetic Account Type that does not require one will result in the account number being ignored.
        /// </summary>
        [JsonProperty("account_number")]
        public string? AccountNumber { get; set; } = null;

        /// <summary>
        /// A reason for the Synthetic Account metadata change.
        /// </summary>
        [JsonProperty("note")]
        public string? Note { get; set; }

        /// <summary>
        /// Contains ACH-specific information. Only populated if the Synthetic Account is in the `ach_external` category.
        /// </summary>
        [JsonProperty("ach")]
        public UpdateSyntheticAccountAchRequest? Ach { get; set; }

        /// <summary>
        /// Contains Instant Payment-specific information. Only populated if the Synthetic Account is in the `instant_payment_external` category.
        /// </summary>
        [JsonProperty("instant_payment")]
        public UpdateSyntheticAccountInstantPaymentRequest? InstantPayment { get; set; }

        /// <summary>
        /// Contains wire-specific information. Only populated if the Synthetic Account is in the `wire_external` category.
        /// </summary>
        [JsonProperty("wire")]
        public UpdateSyntheticAccountWireRequest? Wire { get; set; }
    }
}