//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Newline53.Sdk.Models.Requests
{
    using Newline53.Sdk.Models.Requests;
    using Newline53.Sdk.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class UpdateSyntheticAccountCounterpartyAddressUnionType
    {
        private UpdateSyntheticAccountCounterpartyAddressUnionType(string value)
        {
            Value = value;
        }

        public string Value { get; private set; }

        public static UpdateSyntheticAccountCounterpartyAddressUnionType UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress
        {
            get {
                return new UpdateSyntheticAccountCounterpartyAddressUnionType("updateSyntheticAccount_counterparty_address_Unstructured Address");
            }
        }

        public static UpdateSyntheticAccountCounterpartyAddressUnionType UpdateSyntheticAccountStructuredAddress
        {
            get {
                return new UpdateSyntheticAccountCounterpartyAddressUnionType("updateSyntheticAccount_Structured Address");
            }
        }

        public static UpdateSyntheticAccountCounterpartyAddressUnionType Null
        {
            get {
                return new UpdateSyntheticAccountCounterpartyAddressUnionType("null");
            }
        }

        public override string ToString()
        {
            return Value;
        }
        public static implicit operator String(UpdateSyntheticAccountCounterpartyAddressUnionType v)
        {
            return v.Value;
        }
        public static UpdateSyntheticAccountCounterpartyAddressUnionType FromString(string v)
        {
            switch (v)
            {
                case "updateSyntheticAccount_counterparty_address_Unstructured Address":
                    return UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress;
                case "updateSyntheticAccount_Structured Address":
                    return UpdateSyntheticAccountStructuredAddress;
                case "null":
                    return Null;
                default:
                    throw new ArgumentException("Invalid value for UpdateSyntheticAccountCounterpartyAddressUnionType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((UpdateSyntheticAccountCounterpartyAddressUnionType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    /// <summary>
    /// Address of the business or individual who owns the external account. The accepted format depends on your program's wire address configuration (`unstructured`, `structured`, or `both`). Unstructured format uses `line1`/`line2`/`line3`/`country`. Structured format uses `building_number`/`street_name`/`city`/`postal_code`/`state`/`country` (with `city` and `country` required).
    /// </summary>
    [JsonConverter(typeof(UpdateSyntheticAccountCounterpartyAddressUnion.UpdateSyntheticAccountCounterpartyAddressUnionConverter))]
    public class UpdateSyntheticAccountCounterpartyAddressUnion
    {
        public UpdateSyntheticAccountCounterpartyAddressUnion(UpdateSyntheticAccountCounterpartyAddressUnionType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress? UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public UpdateSyntheticAccountStructuredAddress? UpdateSyntheticAccountStructuredAddress { get; set; }

        public UpdateSyntheticAccountCounterpartyAddressUnionType Type { get; set; }
        public static UpdateSyntheticAccountCounterpartyAddressUnion CreateUpdateSyntheticAccountCounterpartyAddressUnstructuredAddress(UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress updateSyntheticAccountCounterpartyAddressUnstructuredAddress)
        {
            UpdateSyntheticAccountCounterpartyAddressUnionType typ = UpdateSyntheticAccountCounterpartyAddressUnionType.UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress;

            UpdateSyntheticAccountCounterpartyAddressUnion res = new UpdateSyntheticAccountCounterpartyAddressUnion(typ);
            res.UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress = updateSyntheticAccountCounterpartyAddressUnstructuredAddress;
            return res;
        }
        public static UpdateSyntheticAccountCounterpartyAddressUnion CreateUpdateSyntheticAccountStructuredAddress(UpdateSyntheticAccountStructuredAddress updateSyntheticAccountStructuredAddress)
        {
            UpdateSyntheticAccountCounterpartyAddressUnionType typ = UpdateSyntheticAccountCounterpartyAddressUnionType.UpdateSyntheticAccountStructuredAddress;

            UpdateSyntheticAccountCounterpartyAddressUnion res = new UpdateSyntheticAccountCounterpartyAddressUnion(typ);
            res.UpdateSyntheticAccountStructuredAddress = updateSyntheticAccountStructuredAddress;
            return res;
        }

        public static UpdateSyntheticAccountCounterpartyAddressUnion CreateNull()
        {
            UpdateSyntheticAccountCounterpartyAddressUnionType typ = UpdateSyntheticAccountCounterpartyAddressUnionType.Null;
            return new UpdateSyntheticAccountCounterpartyAddressUnion(typ);
        }

        public class UpdateSyntheticAccountCounterpartyAddressUnionConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(UpdateSyntheticAccountCounterpartyAddressUnion);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new UpdateSyntheticAccountCounterpartyAddressUnion(UpdateSyntheticAccountCounterpartyAddressUnionType.UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress) {
                        UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress), new UpdateSyntheticAccountCounterpartyAddressUnion(UpdateSyntheticAccountCounterpartyAddressUnionType.UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress), "UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new UpdateSyntheticAccountCounterpartyAddressUnion(UpdateSyntheticAccountCounterpartyAddressUnionType.UpdateSyntheticAccountStructuredAddress) {
                        UpdateSyntheticAccountStructuredAddress = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<UpdateSyntheticAccountStructuredAddress>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(UpdateSyntheticAccountStructuredAddress), new UpdateSyntheticAccountCounterpartyAddressUnion(UpdateSyntheticAccountCounterpartyAddressUnionType.UpdateSyntheticAccountStructuredAddress), "UpdateSyntheticAccountStructuredAddress"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach (var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                UpdateSyntheticAccountCounterpartyAddressUnion res = (UpdateSyntheticAccountCounterpartyAddressUnion)value;
                if (UpdateSyntheticAccountCounterpartyAddressUnionType.FromString(res.Type).Equals(UpdateSyntheticAccountCounterpartyAddressUnionType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.UpdateSyntheticAccountCounterpartyAddressUnstructuredAddress));
                    return;
                }

                if (res.UpdateSyntheticAccountStructuredAddress != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.UpdateSyntheticAccountStructuredAddress));
                    return;
                }

                throw new InvalidOperationException(
                    "Could not serialize union to JSON: no variant value was set. " +
                    "Construct this union using one of the Create* factory methods."
                );
            }
        }
    }
}